// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2020.1
// Copyright (C) 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "sha256_transform.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic sha256_transform::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic sha256_transform::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<15> sha256_transform::ap_ST_fsm_state1 = "1";
const sc_lv<15> sha256_transform::ap_ST_fsm_state2 = "10";
const sc_lv<15> sha256_transform::ap_ST_fsm_state3 = "100";
const sc_lv<15> sha256_transform::ap_ST_fsm_state4 = "1000";
const sc_lv<15> sha256_transform::ap_ST_fsm_state5 = "10000";
const sc_lv<15> sha256_transform::ap_ST_fsm_state6 = "100000";
const sc_lv<15> sha256_transform::ap_ST_fsm_state7 = "1000000";
const sc_lv<15> sha256_transform::ap_ST_fsm_state8 = "10000000";
const sc_lv<15> sha256_transform::ap_ST_fsm_state9 = "100000000";
const sc_lv<15> sha256_transform::ap_ST_fsm_state10 = "1000000000";
const sc_lv<15> sha256_transform::ap_ST_fsm_state11 = "10000000000";
const sc_lv<15> sha256_transform::ap_ST_fsm_state12 = "100000000000";
const sc_lv<15> sha256_transform::ap_ST_fsm_state13 = "1000000000000";
const sc_lv<15> sha256_transform::ap_ST_fsm_state14 = "10000000000000";
const sc_lv<15> sha256_transform::ap_ST_fsm_state15 = "100000000000000";
const sc_lv<32> sha256_transform::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<32> sha256_transform::ap_const_lv32_1 = "1";
const sc_lv<1> sha256_transform::ap_const_lv1_0 = "0";
const sc_lv<32> sha256_transform::ap_const_lv32_3 = "11";
const sc_lv<1> sha256_transform::ap_const_lv1_1 = "1";
const sc_lv<32> sha256_transform::ap_const_lv32_4 = "100";
const sc_lv<32> sha256_transform::ap_const_lv32_5 = "101";
const sc_lv<32> sha256_transform::ap_const_lv32_6 = "110";
const sc_lv<32> sha256_transform::ap_const_lv32_7 = "111";
const sc_lv<32> sha256_transform::ap_const_lv32_8 = "1000";
const sc_lv<32> sha256_transform::ap_const_lv32_9 = "1001";
const sc_lv<32> sha256_transform::ap_const_lv32_A = "1010";
const sc_lv<32> sha256_transform::ap_const_lv32_B = "1011";
const sc_lv<32> sha256_transform::ap_const_lv32_2 = "10";
const sc_lv<7> sha256_transform::ap_const_lv7_0 = "0000000";
const sc_lv<5> sha256_transform::ap_const_lv5_0 = "00000";
const sc_lv<7> sha256_transform::ap_const_lv7_10 = "10000";
const sc_lv<64> sha256_transform::ap_const_lv64_0 = "0000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<64> sha256_transform::ap_const_lv64_1 = "1";
const sc_lv<64> sha256_transform::ap_const_lv64_2 = "10";
const sc_lv<64> sha256_transform::ap_const_lv64_3 = "11";
const sc_lv<64> sha256_transform::ap_const_lv64_4 = "100";
const sc_lv<64> sha256_transform::ap_const_lv64_5 = "101";
const sc_lv<64> sha256_transform::ap_const_lv64_6 = "110";
const sc_lv<64> sha256_transform::ap_const_lv64_7 = "111";
const sc_lv<32> sha256_transform::ap_const_lv32_C = "1100";
const sc_lv<32> sha256_transform::ap_const_lv32_D = "1101";
const sc_lv<32> sha256_transform::ap_const_lv32_E = "1110";
const sc_lv<5> sha256_transform::ap_const_lv5_10 = "10000";
const sc_lv<5> sha256_transform::ap_const_lv5_1 = "1";
const sc_lv<6> sha256_transform::ap_const_lv6_3 = "11";
const sc_lv<7> sha256_transform::ap_const_lv7_4 = "100";
const sc_lv<7> sha256_transform::ap_const_lv7_40 = "1000000";
const sc_lv<6> sha256_transform::ap_const_lv6_3E = "111110";
const sc_lv<6> sha256_transform::ap_const_lv6_39 = "111001";
const sc_lv<6> sha256_transform::ap_const_lv6_31 = "110001";
const sc_lv<6> sha256_transform::ap_const_lv6_30 = "110000";
const sc_lv<32> sha256_transform::ap_const_lv32_11 = "10001";
const sc_lv<32> sha256_transform::ap_const_lv32_1F = "11111";
const sc_lv<32> sha256_transform::ap_const_lv32_13 = "10011";
const sc_lv<32> sha256_transform::ap_const_lv32_12 = "10010";
const sc_lv<7> sha256_transform::ap_const_lv7_1 = "1";
const sc_lv<32> sha256_transform::ap_const_lv32_19 = "11001";
const sc_lv<32> sha256_transform::ap_const_lv32_FFFFFFFF = "11111111111111111111111111111111";
const sc_lv<32> sha256_transform::ap_const_lv32_16 = "10110";
const bool sha256_transform::ap_const_boolean_1 = true;

sha256_transform::sha256_transform(sc_module_name name) : sc_module(name), mVcdFile(0) {
    K_V_U = new sha256_transform_cud("K_V_U");
    K_V_U->clk(ap_clk);
    K_V_U->reset(ap_rst);
    K_V_U->address0(K_V_address0);
    K_V_U->ce0(K_V_ce0);
    K_V_U->q0(K_V_q0);
    m_V_U = new sha256_transform_dEe("m_V_U");
    m_V_U->clk(ap_clk);
    m_V_U->reset(ap_rst);
    m_V_U->address0(m_V_address0);
    m_V_U->ce0(m_V_ce0);
    m_V_U->we0(m_V_we0);
    m_V_U->d0(m_V_d0);
    m_V_U->q0(m_V_q0);
    m_V_U->address1(m_V_address1);
    m_V_U->ce1(m_V_ce1);
    m_V_U->we1(m_V_we1);
    m_V_U->d1(m_V_d1);
    m_V_U->q1(m_V_q1);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_K_V_address0);
    sensitive << ( ap_CS_fsm_state11 );
    sensitive << ( zext_ln544_6_fu_819_p1 );

    SC_METHOD(thread_K_V_ce0);
    sensitive << ( ap_CS_fsm_state11 );

    SC_METHOD(thread_a_V_2_fu_999_p2);
    sensitive << ( ret_V_64_reg_1192 );
    sensitive << ( add_ln209_16_fu_993_p2 );

    SC_METHOD(thread_add_ln209_10_fu_686_p2);
    sensitive << ( ret_V_44_fu_605_p2 );
    sensitive << ( ret_V_49_fu_675_p2 );

    SC_METHOD(thread_add_ln209_11_fu_898_p2);
    sensitive << ( K_V_q0 );
    sensitive << ( m_V_q0 );

    SC_METHOD(thread_add_ln209_12_fu_825_p2);
    sensitive << ( ret_V_57_fu_813_p2 );
    sensitive << ( ret_V_54_fu_789_p2 );

    SC_METHOD(thread_add_ln209_13_fu_831_p2);
    sensitive << ( p_01439_0_reg_429 );
    sensitive << ( add_ln209_12_fu_825_p2 );

    SC_METHOD(thread_add_ln209_16_fu_993_p2);
    sensitive << ( t1_V_fu_904_p2 );
    sensitive << ( ret_V_61_fu_981_p2 );

    SC_METHOD(thread_add_ln209_fu_681_p2);
    sensitive << ( m_V_q0 );
    sensitive << ( m_V_load_1_reg_1071 );

    SC_METHOD(thread_add_ln700_10_fu_893_p2);
    sensitive << ( h_V_reg_1163 );
    sensitive << ( p_01439_0_reg_429 );

    SC_METHOD(thread_add_ln700_3_fu_861_p2);
    sensitive << ( a_V_reg_1091 );
    sensitive << ( lhs_V_20_reg_354 );

    SC_METHOD(thread_add_ln700_4_fu_867_p2);
    sensitive << ( b_V_reg_1097 );
    sensitive << ( rhs_V_33_reg_364 );

    SC_METHOD(thread_add_ln700_5_fu_873_p2);
    sensitive << ( c_V_reg_1113 );
    sensitive << ( rhs_V_34_reg_375 );

    SC_METHOD(thread_add_ln700_6_fu_1004_p2);
    sensitive << ( d_V_reg_1119 );
    sensitive << ( p_01587_0_reg_386 );

    SC_METHOD(thread_add_ln700_7_fu_878_p2);
    sensitive << ( e_V_reg_1135 );
    sensitive << ( lhs_V_reg_397 );

    SC_METHOD(thread_add_ln700_8_fu_883_p2);
    sensitive << ( f_V_reg_1141 );
    sensitive << ( rhs_V_reg_407 );

    SC_METHOD(thread_add_ln700_9_fu_888_p2);
    sensitive << ( g_V_reg_1157 );
    sensitive << ( rhs_V_32_reg_418 );

    SC_METHOD(thread_add_ln700_fu_445_p2);
    sensitive << ( p_01115_0_reg_319 );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state10);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state11);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state12);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state13);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state14);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state15);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state3);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state4);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state5);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state6);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state7);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state8);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state9);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state15 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_CS_fsm_state15 );

    SC_METHOD(thread_data_V_address0);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( zext_ln1356_fu_468_p1 );

    SC_METHOD(thread_data_V_ce0);
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_e_V_2_fu_987_p2);
    sensitive << ( p_01587_0_reg_386 );
    sensitive << ( t1_V_fu_904_p2 );

    SC_METHOD(thread_i_V_2_fu_711_p2);
    sensitive << ( p_01115_2_reg_343 );

    SC_METHOD(thread_i_V_fu_699_p2);
    sensitive << ( p_01115_1_reg_331 );

    SC_METHOD(thread_icmp_ln40_fu_489_p2);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( p_01115_1_reg_331 );

    SC_METHOD(thread_icmp_ln887_1_fu_705_p2);
    sensitive << ( ap_CS_fsm_state11 );
    sensitive << ( p_01115_2_reg_343 );

    SC_METHOD(thread_icmp_ln887_fu_439_p2);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( p_01115_0_reg_319 );

    SC_METHOD(thread_j_V_fu_473_p2);
    sensitive << ( p_0262_0_reg_308 );

    SC_METHOD(thread_m_V_address0);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( ap_CS_fsm_state11 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( zext_ln544_fu_479_p1 );
    sensitive << ( zext_ln544_8_fu_505_p1 );
    sensitive << ( zext_ln544_11_fu_536_p1 );
    sensitive << ( zext_ln544_6_fu_819_p1 );

    SC_METHOD(thread_m_V_address1);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( zext_ln544_9_fu_516_p1 );
    sensitive << ( zext_ln544_10_fu_526_p1 );
    sensitive << ( zext_ln544_5_fu_541_p1 );

    SC_METHOD(thread_m_V_ce0);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( ap_CS_fsm_state11 );
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_m_V_ce1);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( ap_CS_fsm_state6 );

    SC_METHOD(thread_m_V_d0);
    sensitive << ( data_V_q0 );
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_m_V_d1);
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( add_ln209_10_fu_686_p2 );
    sensitive << ( add_ln209_fu_681_p2 );

    SC_METHOD(thread_m_V_we0);
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_m_V_we1);
    sensitive << ( ap_CS_fsm_state6 );

    SC_METHOD(thread_r_V_11_fu_586_p4);
    sensitive << ( m_V_load_reg_1062 );

    SC_METHOD(thread_r_V_12_fu_611_p4);
    sensitive << ( m_V_q1 );

    SC_METHOD(thread_r_V_13_fu_633_p4);
    sensitive << ( m_V_q1 );

    SC_METHOD(thread_r_V_14_fu_655_p4);
    sensitive << ( m_V_q1 );

    SC_METHOD(thread_r_V_15_fu_717_p4);
    sensitive << ( lhs_V_reg_397 );

    SC_METHOD(thread_r_V_16_fu_739_p4);
    sensitive << ( lhs_V_reg_397 );

    SC_METHOD(thread_r_V_17_fu_761_p4);
    sensitive << ( lhs_V_reg_397 );

    SC_METHOD(thread_r_V_18_fu_909_p4);
    sensitive << ( lhs_V_20_reg_354 );

    SC_METHOD(thread_r_V_19_fu_931_p4);
    sensitive << ( lhs_V_20_reg_354 );

    SC_METHOD(thread_r_V_20_fu_953_p4);
    sensitive << ( lhs_V_20_reg_354 );

    SC_METHOD(thread_r_V_24_fu_595_p1);
    sensitive << ( r_V_11_fu_586_p4 );

    SC_METHOD(thread_r_V_25_fu_665_p1);
    sensitive << ( r_V_14_fu_655_p4 );

    SC_METHOD(thread_r_V_26_fu_801_p2);
    sensitive << ( lhs_V_reg_397 );

    SC_METHOD(thread_r_V_fu_546_p4);
    sensitive << ( m_V_load_reg_1062 );

    SC_METHOD(thread_r_V_s_fu_566_p4);
    sensitive << ( m_V_load_reg_1062 );

    SC_METHOD(thread_ret_V_41_fu_499_p2);
    sensitive << ( trunc_ln215_2_fu_495_p1 );

    SC_METHOD(thread_ret_V_44_fu_605_p2);
    sensitive << ( xor_ln1357_fu_599_p2 );
    sensitive << ( ret_V_65_fu_558_p3 );

    SC_METHOD(thread_ret_V_45_fu_510_p2);
    sensitive << ( trunc_ln215_2_fu_495_p1 );

    SC_METHOD(thread_ret_V_46_fu_521_p2);
    sensitive << ( trunc_ln215_2_reg_1041 );

    SC_METHOD(thread_ret_V_49_fu_675_p2);
    sensitive << ( xor_ln1357_12_fu_669_p2 );
    sensitive << ( ret_V_67_fu_625_p3 );

    SC_METHOD(thread_ret_V_50_fu_531_p2);
    sensitive << ( trunc_ln215_2_reg_1041 );

    SC_METHOD(thread_ret_V_54_fu_789_p2);
    sensitive << ( xor_ln1357_14_fu_783_p2 );
    sensitive << ( ret_V_71_fu_775_p3 );

    SC_METHOD(thread_ret_V_57_fu_813_p2);
    sensitive << ( ret_V_73_fu_807_p2 );
    sensitive << ( ret_V_72_fu_795_p2 );

    SC_METHOD(thread_ret_V_61_fu_981_p2);
    sensitive << ( xor_ln1357_17_fu_975_p2 );
    sensitive << ( ret_V_76_fu_967_p3 );

    SC_METHOD(thread_ret_V_64_fu_855_p2);
    sensitive << ( ret_V_77_fu_843_p2 );
    sensitive << ( ret_V_78_fu_849_p2 );

    SC_METHOD(thread_ret_V_65_fu_558_p3);
    sensitive << ( trunc_ln1503_fu_555_p1 );
    sensitive << ( r_V_fu_546_p4 );

    SC_METHOD(thread_ret_V_66_fu_578_p3);
    sensitive << ( trunc_ln1503_10_fu_575_p1 );
    sensitive << ( r_V_s_fu_566_p4 );

    SC_METHOD(thread_ret_V_67_fu_625_p3);
    sensitive << ( trunc_ln1503_11_fu_621_p1 );
    sensitive << ( r_V_12_fu_611_p4 );

    SC_METHOD(thread_ret_V_68_fu_647_p3);
    sensitive << ( trunc_ln1503_12_fu_643_p1 );
    sensitive << ( r_V_13_fu_633_p4 );

    SC_METHOD(thread_ret_V_69_fu_731_p3);
    sensitive << ( trunc_ln1503_13_fu_727_p1 );
    sensitive << ( r_V_15_fu_717_p4 );

    SC_METHOD(thread_ret_V_70_fu_753_p3);
    sensitive << ( trunc_ln1503_14_fu_749_p1 );
    sensitive << ( r_V_16_fu_739_p4 );

    SC_METHOD(thread_ret_V_71_fu_775_p3);
    sensitive << ( trunc_ln1503_15_fu_771_p1 );
    sensitive << ( r_V_17_fu_761_p4 );

    SC_METHOD(thread_ret_V_72_fu_795_p2);
    sensitive << ( lhs_V_reg_397 );
    sensitive << ( rhs_V_reg_407 );

    SC_METHOD(thread_ret_V_73_fu_807_p2);
    sensitive << ( rhs_V_32_reg_418 );
    sensitive << ( r_V_26_fu_801_p2 );

    SC_METHOD(thread_ret_V_74_fu_923_p3);
    sensitive << ( trunc_ln1503_16_fu_919_p1 );
    sensitive << ( r_V_18_fu_909_p4 );

    SC_METHOD(thread_ret_V_75_fu_945_p3);
    sensitive << ( trunc_ln1503_17_fu_941_p1 );
    sensitive << ( r_V_19_fu_931_p4 );

    SC_METHOD(thread_ret_V_76_fu_967_p3);
    sensitive << ( trunc_ln1503_18_fu_963_p1 );
    sensitive << ( r_V_20_fu_953_p4 );

    SC_METHOD(thread_ret_V_77_fu_843_p2);
    sensitive << ( lhs_V_20_reg_354 );
    sensitive << ( xor_ln1357_9_fu_837_p2 );

    SC_METHOD(thread_ret_V_78_fu_849_p2);
    sensitive << ( rhs_V_33_reg_364 );
    sensitive << ( rhs_V_34_reg_375 );

    SC_METHOD(thread_ret_V_fu_455_p2);
    sensitive << ( trunc_ln215_fu_451_p1 );

    SC_METHOD(thread_state_V_addr_10_reg_1108);
    sensitive << ( ap_CS_fsm_state7 );

    SC_METHOD(thread_state_V_addr_11_reg_1125);
    sensitive << ( ap_CS_fsm_state8 );

    SC_METHOD(thread_state_V_addr_12_reg_1130);
    sensitive << ( ap_CS_fsm_state8 );

    SC_METHOD(thread_state_V_addr_13_reg_1147);
    sensitive << ( ap_CS_fsm_state9 );

    SC_METHOD(thread_state_V_addr_14_reg_1152);
    sensitive << ( ap_CS_fsm_state9 );

    SC_METHOD(thread_state_V_addr_8_reg_1057);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( icmp_ln40_fu_489_p2 );

    SC_METHOD(thread_state_V_addr_9_reg_1103);
    sensitive << ( ap_CS_fsm_state7 );

    SC_METHOD(thread_state_V_address0);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( state_V_addr_9_reg_1103 );
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( state_V_addr_11_reg_1125 );
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( state_V_addr_13_reg_1147 );
    sensitive << ( ap_CS_fsm_state11 );
    sensitive << ( ap_CS_fsm_state13 );
    sensitive << ( ap_CS_fsm_state14 );
    sensitive << ( ap_CS_fsm_state15 );

    SC_METHOD(thread_state_V_address1);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( state_V_addr_8_reg_1057 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( state_V_addr_10_reg_1108 );
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( state_V_addr_12_reg_1130 );
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( state_V_addr_14_reg_1152 );
    sensitive << ( ap_CS_fsm_state11 );
    sensitive << ( ap_CS_fsm_state13 );
    sensitive << ( ap_CS_fsm_state14 );
    sensitive << ( ap_CS_fsm_state15 );

    SC_METHOD(thread_state_V_ce0);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( ap_CS_fsm_state11 );
    sensitive << ( ap_CS_fsm_state13 );
    sensitive << ( ap_CS_fsm_state14 );
    sensitive << ( ap_CS_fsm_state15 );

    SC_METHOD(thread_state_V_ce1);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( ap_CS_fsm_state11 );
    sensitive << ( ap_CS_fsm_state13 );
    sensitive << ( ap_CS_fsm_state14 );
    sensitive << ( ap_CS_fsm_state15 );

    SC_METHOD(thread_state_V_d0);
    sensitive << ( ap_CS_fsm_state11 );
    sensitive << ( add_ln700_5_reg_1197 );
    sensitive << ( add_ln700_7_reg_1202 );
    sensitive << ( add_ln700_9_reg_1212 );
    sensitive << ( add_ln700_3_fu_861_p2 );
    sensitive << ( ap_CS_fsm_state13 );
    sensitive << ( ap_CS_fsm_state14 );
    sensitive << ( ap_CS_fsm_state15 );

    SC_METHOD(thread_state_V_d1);
    sensitive << ( ap_CS_fsm_state11 );
    sensitive << ( add_ln700_8_reg_1207 );
    sensitive << ( add_ln700_10_reg_1217 );
    sensitive << ( add_ln700_4_fu_867_p2 );
    sensitive << ( ap_CS_fsm_state13 );
    sensitive << ( add_ln700_6_fu_1004_p2 );
    sensitive << ( ap_CS_fsm_state14 );
    sensitive << ( ap_CS_fsm_state15 );

    SC_METHOD(thread_state_V_we0);
    sensitive << ( ap_CS_fsm_state11 );
    sensitive << ( icmp_ln887_1_fu_705_p2 );
    sensitive << ( ap_CS_fsm_state13 );
    sensitive << ( ap_CS_fsm_state14 );
    sensitive << ( ap_CS_fsm_state15 );

    SC_METHOD(thread_state_V_we1);
    sensitive << ( ap_CS_fsm_state11 );
    sensitive << ( icmp_ln887_1_fu_705_p2 );
    sensitive << ( ap_CS_fsm_state13 );
    sensitive << ( ap_CS_fsm_state14 );
    sensitive << ( ap_CS_fsm_state15 );

    SC_METHOD(thread_t1_V_fu_904_p2);
    sensitive << ( add_ln209_13_reg_1187 );
    sensitive << ( add_ln209_11_fu_898_p2 );

    SC_METHOD(thread_tmp_fu_461_p3);
    sensitive << ( data_V_offset );
    sensitive << ( ret_V_fu_455_p2 );

    SC_METHOD(thread_trunc_ln1503_10_fu_575_p1);
    sensitive << ( m_V_load_reg_1062 );

    SC_METHOD(thread_trunc_ln1503_11_fu_621_p1);
    sensitive << ( m_V_q1 );

    SC_METHOD(thread_trunc_ln1503_12_fu_643_p1);
    sensitive << ( m_V_q1 );

    SC_METHOD(thread_trunc_ln1503_13_fu_727_p1);
    sensitive << ( lhs_V_reg_397 );

    SC_METHOD(thread_trunc_ln1503_14_fu_749_p1);
    sensitive << ( lhs_V_reg_397 );

    SC_METHOD(thread_trunc_ln1503_15_fu_771_p1);
    sensitive << ( lhs_V_reg_397 );

    SC_METHOD(thread_trunc_ln1503_16_fu_919_p1);
    sensitive << ( lhs_V_20_reg_354 );

    SC_METHOD(thread_trunc_ln1503_17_fu_941_p1);
    sensitive << ( lhs_V_20_reg_354 );

    SC_METHOD(thread_trunc_ln1503_18_fu_963_p1);
    sensitive << ( lhs_V_20_reg_354 );

    SC_METHOD(thread_trunc_ln1503_fu_555_p1);
    sensitive << ( m_V_load_reg_1062 );

    SC_METHOD(thread_trunc_ln215_2_fu_495_p1);
    sensitive << ( p_01115_1_reg_331 );

    SC_METHOD(thread_trunc_ln215_fu_451_p1);
    sensitive << ( p_0262_0_reg_308 );

    SC_METHOD(thread_xor_ln1357_12_fu_669_p2);
    sensitive << ( r_V_25_fu_665_p1 );
    sensitive << ( ret_V_68_fu_647_p3 );

    SC_METHOD(thread_xor_ln1357_14_fu_783_p2);
    sensitive << ( ret_V_69_fu_731_p3 );
    sensitive << ( ret_V_70_fu_753_p3 );

    SC_METHOD(thread_xor_ln1357_17_fu_975_p2);
    sensitive << ( ret_V_74_fu_923_p3 );
    sensitive << ( ret_V_75_fu_945_p3 );

    SC_METHOD(thread_xor_ln1357_9_fu_837_p2);
    sensitive << ( rhs_V_33_reg_364 );
    sensitive << ( rhs_V_34_reg_375 );

    SC_METHOD(thread_xor_ln1357_fu_599_p2);
    sensitive << ( r_V_24_fu_595_p1 );
    sensitive << ( ret_V_66_fu_578_p3 );

    SC_METHOD(thread_zext_ln1356_fu_468_p1);
    sensitive << ( tmp_fu_461_p3 );

    SC_METHOD(thread_zext_ln544_10_fu_526_p1);
    sensitive << ( ret_V_46_fu_521_p2 );

    SC_METHOD(thread_zext_ln544_11_fu_536_p1);
    sensitive << ( ret_V_50_fu_531_p2 );

    SC_METHOD(thread_zext_ln544_5_fu_541_p1);
    sensitive << ( p_01115_1_reg_331 );

    SC_METHOD(thread_zext_ln544_6_fu_819_p1);
    sensitive << ( p_01115_2_reg_343 );

    SC_METHOD(thread_zext_ln544_8_fu_505_p1);
    sensitive << ( ret_V_41_fu_499_p2 );

    SC_METHOD(thread_zext_ln544_9_fu_516_p1);
    sensitive << ( ret_V_45_fu_510_p2 );

    SC_METHOD(thread_zext_ln544_fu_479_p1);
    sensitive << ( p_01115_0_reg_319 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( icmp_ln887_fu_439_p2 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( icmp_ln40_fu_489_p2 );
    sensitive << ( ap_CS_fsm_state11 );
    sensitive << ( icmp_ln887_1_fu_705_p2 );

    ap_CS_fsm = "000000000000001";
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "sha256_transform_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, state_V_address0, "(port)state_V_address0");
    sc_trace(mVcdFile, state_V_ce0, "(port)state_V_ce0");
    sc_trace(mVcdFile, state_V_we0, "(port)state_V_we0");
    sc_trace(mVcdFile, state_V_d0, "(port)state_V_d0");
    sc_trace(mVcdFile, state_V_q0, "(port)state_V_q0");
    sc_trace(mVcdFile, state_V_address1, "(port)state_V_address1");
    sc_trace(mVcdFile, state_V_ce1, "(port)state_V_ce1");
    sc_trace(mVcdFile, state_V_we1, "(port)state_V_we1");
    sc_trace(mVcdFile, state_V_d1, "(port)state_V_d1");
    sc_trace(mVcdFile, state_V_q1, "(port)state_V_q1");
    sc_trace(mVcdFile, data_V_address0, "(port)data_V_address0");
    sc_trace(mVcdFile, data_V_ce0, "(port)data_V_ce0");
    sc_trace(mVcdFile, data_V_q0, "(port)data_V_q0");
    sc_trace(mVcdFile, data_V_offset, "(port)data_V_offset");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, K_V_address0, "K_V_address0");
    sc_trace(mVcdFile, K_V_ce0, "K_V_ce0");
    sc_trace(mVcdFile, K_V_q0, "K_V_q0");
    sc_trace(mVcdFile, add_ln700_fu_445_p2, "add_ln700_fu_445_p2");
    sc_trace(mVcdFile, add_ln700_reg_1023, "add_ln700_reg_1023");
    sc_trace(mVcdFile, ap_CS_fsm_state2, "ap_CS_fsm_state2");
    sc_trace(mVcdFile, icmp_ln887_fu_439_p2, "icmp_ln887_fu_439_p2");
    sc_trace(mVcdFile, j_V_fu_473_p2, "j_V_fu_473_p2");
    sc_trace(mVcdFile, j_V_reg_1033, "j_V_reg_1033");
    sc_trace(mVcdFile, trunc_ln215_2_fu_495_p1, "trunc_ln215_2_fu_495_p1");
    sc_trace(mVcdFile, trunc_ln215_2_reg_1041, "trunc_ln215_2_reg_1041");
    sc_trace(mVcdFile, ap_CS_fsm_state4, "ap_CS_fsm_state4");
    sc_trace(mVcdFile, icmp_ln40_fu_489_p2, "icmp_ln40_fu_489_p2");
    sc_trace(mVcdFile, state_V_addr_8_reg_1057, "state_V_addr_8_reg_1057");
    sc_trace(mVcdFile, m_V_q0, "m_V_q0");
    sc_trace(mVcdFile, m_V_load_reg_1062, "m_V_load_reg_1062");
    sc_trace(mVcdFile, ap_CS_fsm_state5, "ap_CS_fsm_state5");
    sc_trace(mVcdFile, m_V_q1, "m_V_q1");
    sc_trace(mVcdFile, m_V_load_1_reg_1071, "m_V_load_1_reg_1071");
    sc_trace(mVcdFile, i_V_fu_699_p2, "i_V_fu_699_p2");
    sc_trace(mVcdFile, ap_CS_fsm_state6, "ap_CS_fsm_state6");
    sc_trace(mVcdFile, a_V_reg_1091, "a_V_reg_1091");
    sc_trace(mVcdFile, ap_CS_fsm_state7, "ap_CS_fsm_state7");
    sc_trace(mVcdFile, b_V_reg_1097, "b_V_reg_1097");
    sc_trace(mVcdFile, state_V_addr_9_reg_1103, "state_V_addr_9_reg_1103");
    sc_trace(mVcdFile, state_V_addr_10_reg_1108, "state_V_addr_10_reg_1108");
    sc_trace(mVcdFile, c_V_reg_1113, "c_V_reg_1113");
    sc_trace(mVcdFile, ap_CS_fsm_state8, "ap_CS_fsm_state8");
    sc_trace(mVcdFile, d_V_reg_1119, "d_V_reg_1119");
    sc_trace(mVcdFile, state_V_addr_11_reg_1125, "state_V_addr_11_reg_1125");
    sc_trace(mVcdFile, state_V_addr_12_reg_1130, "state_V_addr_12_reg_1130");
    sc_trace(mVcdFile, e_V_reg_1135, "e_V_reg_1135");
    sc_trace(mVcdFile, ap_CS_fsm_state9, "ap_CS_fsm_state9");
    sc_trace(mVcdFile, f_V_reg_1141, "f_V_reg_1141");
    sc_trace(mVcdFile, state_V_addr_13_reg_1147, "state_V_addr_13_reg_1147");
    sc_trace(mVcdFile, state_V_addr_14_reg_1152, "state_V_addr_14_reg_1152");
    sc_trace(mVcdFile, g_V_reg_1157, "g_V_reg_1157");
    sc_trace(mVcdFile, ap_CS_fsm_state10, "ap_CS_fsm_state10");
    sc_trace(mVcdFile, h_V_reg_1163, "h_V_reg_1163");
    sc_trace(mVcdFile, i_V_2_fu_711_p2, "i_V_2_fu_711_p2");
    sc_trace(mVcdFile, i_V_2_reg_1172, "i_V_2_reg_1172");
    sc_trace(mVcdFile, ap_CS_fsm_state11, "ap_CS_fsm_state11");
    sc_trace(mVcdFile, icmp_ln887_1_fu_705_p2, "icmp_ln887_1_fu_705_p2");
    sc_trace(mVcdFile, add_ln209_13_fu_831_p2, "add_ln209_13_fu_831_p2");
    sc_trace(mVcdFile, add_ln209_13_reg_1187, "add_ln209_13_reg_1187");
    sc_trace(mVcdFile, ret_V_64_fu_855_p2, "ret_V_64_fu_855_p2");
    sc_trace(mVcdFile, ret_V_64_reg_1192, "ret_V_64_reg_1192");
    sc_trace(mVcdFile, add_ln700_5_fu_873_p2, "add_ln700_5_fu_873_p2");
    sc_trace(mVcdFile, add_ln700_5_reg_1197, "add_ln700_5_reg_1197");
    sc_trace(mVcdFile, add_ln700_7_fu_878_p2, "add_ln700_7_fu_878_p2");
    sc_trace(mVcdFile, add_ln700_7_reg_1202, "add_ln700_7_reg_1202");
    sc_trace(mVcdFile, add_ln700_8_fu_883_p2, "add_ln700_8_fu_883_p2");
    sc_trace(mVcdFile, add_ln700_8_reg_1207, "add_ln700_8_reg_1207");
    sc_trace(mVcdFile, add_ln700_9_fu_888_p2, "add_ln700_9_fu_888_p2");
    sc_trace(mVcdFile, add_ln700_9_reg_1212, "add_ln700_9_reg_1212");
    sc_trace(mVcdFile, add_ln700_10_fu_893_p2, "add_ln700_10_fu_893_p2");
    sc_trace(mVcdFile, add_ln700_10_reg_1217, "add_ln700_10_reg_1217");
    sc_trace(mVcdFile, e_V_2_fu_987_p2, "e_V_2_fu_987_p2");
    sc_trace(mVcdFile, ap_CS_fsm_state12, "ap_CS_fsm_state12");
    sc_trace(mVcdFile, a_V_2_fu_999_p2, "a_V_2_fu_999_p2");
    sc_trace(mVcdFile, m_V_address0, "m_V_address0");
    sc_trace(mVcdFile, m_V_ce0, "m_V_ce0");
    sc_trace(mVcdFile, m_V_we0, "m_V_we0");
    sc_trace(mVcdFile, m_V_d0, "m_V_d0");
    sc_trace(mVcdFile, m_V_address1, "m_V_address1");
    sc_trace(mVcdFile, m_V_ce1, "m_V_ce1");
    sc_trace(mVcdFile, m_V_we1, "m_V_we1");
    sc_trace(mVcdFile, m_V_d1, "m_V_d1");
    sc_trace(mVcdFile, p_0262_0_reg_308, "p_0262_0_reg_308");
    sc_trace(mVcdFile, ap_CS_fsm_state3, "ap_CS_fsm_state3");
    sc_trace(mVcdFile, p_01115_0_reg_319, "p_01115_0_reg_319");
    sc_trace(mVcdFile, p_01115_1_reg_331, "p_01115_1_reg_331");
    sc_trace(mVcdFile, p_01115_2_reg_343, "p_01115_2_reg_343");
    sc_trace(mVcdFile, lhs_V_20_reg_354, "lhs_V_20_reg_354");
    sc_trace(mVcdFile, rhs_V_33_reg_364, "rhs_V_33_reg_364");
    sc_trace(mVcdFile, rhs_V_34_reg_375, "rhs_V_34_reg_375");
    sc_trace(mVcdFile, p_01587_0_reg_386, "p_01587_0_reg_386");
    sc_trace(mVcdFile, lhs_V_reg_397, "lhs_V_reg_397");
    sc_trace(mVcdFile, rhs_V_reg_407, "rhs_V_reg_407");
    sc_trace(mVcdFile, rhs_V_32_reg_418, "rhs_V_32_reg_418");
    sc_trace(mVcdFile, p_01439_0_reg_429, "p_01439_0_reg_429");
    sc_trace(mVcdFile, zext_ln1356_fu_468_p1, "zext_ln1356_fu_468_p1");
    sc_trace(mVcdFile, zext_ln544_fu_479_p1, "zext_ln544_fu_479_p1");
    sc_trace(mVcdFile, zext_ln544_8_fu_505_p1, "zext_ln544_8_fu_505_p1");
    sc_trace(mVcdFile, zext_ln544_9_fu_516_p1, "zext_ln544_9_fu_516_p1");
    sc_trace(mVcdFile, zext_ln544_10_fu_526_p1, "zext_ln544_10_fu_526_p1");
    sc_trace(mVcdFile, zext_ln544_11_fu_536_p1, "zext_ln544_11_fu_536_p1");
    sc_trace(mVcdFile, zext_ln544_5_fu_541_p1, "zext_ln544_5_fu_541_p1");
    sc_trace(mVcdFile, zext_ln544_6_fu_819_p1, "zext_ln544_6_fu_819_p1");
    sc_trace(mVcdFile, add_ln700_3_fu_861_p2, "add_ln700_3_fu_861_p2");
    sc_trace(mVcdFile, add_ln700_4_fu_867_p2, "add_ln700_4_fu_867_p2");
    sc_trace(mVcdFile, ap_CS_fsm_state13, "ap_CS_fsm_state13");
    sc_trace(mVcdFile, add_ln700_6_fu_1004_p2, "add_ln700_6_fu_1004_p2");
    sc_trace(mVcdFile, ap_CS_fsm_state14, "ap_CS_fsm_state14");
    sc_trace(mVcdFile, ap_CS_fsm_state15, "ap_CS_fsm_state15");
    sc_trace(mVcdFile, trunc_ln215_fu_451_p1, "trunc_ln215_fu_451_p1");
    sc_trace(mVcdFile, ret_V_fu_455_p2, "ret_V_fu_455_p2");
    sc_trace(mVcdFile, tmp_fu_461_p3, "tmp_fu_461_p3");
    sc_trace(mVcdFile, ret_V_41_fu_499_p2, "ret_V_41_fu_499_p2");
    sc_trace(mVcdFile, ret_V_45_fu_510_p2, "ret_V_45_fu_510_p2");
    sc_trace(mVcdFile, ret_V_46_fu_521_p2, "ret_V_46_fu_521_p2");
    sc_trace(mVcdFile, ret_V_50_fu_531_p2, "ret_V_50_fu_531_p2");
    sc_trace(mVcdFile, trunc_ln1503_fu_555_p1, "trunc_ln1503_fu_555_p1");
    sc_trace(mVcdFile, r_V_fu_546_p4, "r_V_fu_546_p4");
    sc_trace(mVcdFile, trunc_ln1503_10_fu_575_p1, "trunc_ln1503_10_fu_575_p1");
    sc_trace(mVcdFile, r_V_s_fu_566_p4, "r_V_s_fu_566_p4");
    sc_trace(mVcdFile, r_V_11_fu_586_p4, "r_V_11_fu_586_p4");
    sc_trace(mVcdFile, r_V_24_fu_595_p1, "r_V_24_fu_595_p1");
    sc_trace(mVcdFile, ret_V_66_fu_578_p3, "ret_V_66_fu_578_p3");
    sc_trace(mVcdFile, xor_ln1357_fu_599_p2, "xor_ln1357_fu_599_p2");
    sc_trace(mVcdFile, ret_V_65_fu_558_p3, "ret_V_65_fu_558_p3");
    sc_trace(mVcdFile, trunc_ln1503_11_fu_621_p1, "trunc_ln1503_11_fu_621_p1");
    sc_trace(mVcdFile, r_V_12_fu_611_p4, "r_V_12_fu_611_p4");
    sc_trace(mVcdFile, trunc_ln1503_12_fu_643_p1, "trunc_ln1503_12_fu_643_p1");
    sc_trace(mVcdFile, r_V_13_fu_633_p4, "r_V_13_fu_633_p4");
    sc_trace(mVcdFile, r_V_14_fu_655_p4, "r_V_14_fu_655_p4");
    sc_trace(mVcdFile, r_V_25_fu_665_p1, "r_V_25_fu_665_p1");
    sc_trace(mVcdFile, ret_V_68_fu_647_p3, "ret_V_68_fu_647_p3");
    sc_trace(mVcdFile, xor_ln1357_12_fu_669_p2, "xor_ln1357_12_fu_669_p2");
    sc_trace(mVcdFile, ret_V_67_fu_625_p3, "ret_V_67_fu_625_p3");
    sc_trace(mVcdFile, ret_V_44_fu_605_p2, "ret_V_44_fu_605_p2");
    sc_trace(mVcdFile, ret_V_49_fu_675_p2, "ret_V_49_fu_675_p2");
    sc_trace(mVcdFile, add_ln209_10_fu_686_p2, "add_ln209_10_fu_686_p2");
    sc_trace(mVcdFile, add_ln209_fu_681_p2, "add_ln209_fu_681_p2");
    sc_trace(mVcdFile, trunc_ln1503_13_fu_727_p1, "trunc_ln1503_13_fu_727_p1");
    sc_trace(mVcdFile, r_V_15_fu_717_p4, "r_V_15_fu_717_p4");
    sc_trace(mVcdFile, trunc_ln1503_14_fu_749_p1, "trunc_ln1503_14_fu_749_p1");
    sc_trace(mVcdFile, r_V_16_fu_739_p4, "r_V_16_fu_739_p4");
    sc_trace(mVcdFile, trunc_ln1503_15_fu_771_p1, "trunc_ln1503_15_fu_771_p1");
    sc_trace(mVcdFile, r_V_17_fu_761_p4, "r_V_17_fu_761_p4");
    sc_trace(mVcdFile, ret_V_69_fu_731_p3, "ret_V_69_fu_731_p3");
    sc_trace(mVcdFile, ret_V_70_fu_753_p3, "ret_V_70_fu_753_p3");
    sc_trace(mVcdFile, xor_ln1357_14_fu_783_p2, "xor_ln1357_14_fu_783_p2");
    sc_trace(mVcdFile, ret_V_71_fu_775_p3, "ret_V_71_fu_775_p3");
    sc_trace(mVcdFile, r_V_26_fu_801_p2, "r_V_26_fu_801_p2");
    sc_trace(mVcdFile, ret_V_73_fu_807_p2, "ret_V_73_fu_807_p2");
    sc_trace(mVcdFile, ret_V_72_fu_795_p2, "ret_V_72_fu_795_p2");
    sc_trace(mVcdFile, ret_V_57_fu_813_p2, "ret_V_57_fu_813_p2");
    sc_trace(mVcdFile, ret_V_54_fu_789_p2, "ret_V_54_fu_789_p2");
    sc_trace(mVcdFile, add_ln209_12_fu_825_p2, "add_ln209_12_fu_825_p2");
    sc_trace(mVcdFile, xor_ln1357_9_fu_837_p2, "xor_ln1357_9_fu_837_p2");
    sc_trace(mVcdFile, ret_V_77_fu_843_p2, "ret_V_77_fu_843_p2");
    sc_trace(mVcdFile, ret_V_78_fu_849_p2, "ret_V_78_fu_849_p2");
    sc_trace(mVcdFile, add_ln209_11_fu_898_p2, "add_ln209_11_fu_898_p2");
    sc_trace(mVcdFile, trunc_ln1503_16_fu_919_p1, "trunc_ln1503_16_fu_919_p1");
    sc_trace(mVcdFile, r_V_18_fu_909_p4, "r_V_18_fu_909_p4");
    sc_trace(mVcdFile, trunc_ln1503_17_fu_941_p1, "trunc_ln1503_17_fu_941_p1");
    sc_trace(mVcdFile, r_V_19_fu_931_p4, "r_V_19_fu_931_p4");
    sc_trace(mVcdFile, trunc_ln1503_18_fu_963_p1, "trunc_ln1503_18_fu_963_p1");
    sc_trace(mVcdFile, r_V_20_fu_953_p4, "r_V_20_fu_953_p4");
    sc_trace(mVcdFile, ret_V_74_fu_923_p3, "ret_V_74_fu_923_p3");
    sc_trace(mVcdFile, ret_V_75_fu_945_p3, "ret_V_75_fu_945_p3");
    sc_trace(mVcdFile, xor_ln1357_17_fu_975_p2, "xor_ln1357_17_fu_975_p2");
    sc_trace(mVcdFile, ret_V_76_fu_967_p3, "ret_V_76_fu_967_p3");
    sc_trace(mVcdFile, t1_V_fu_904_p2, "t1_V_fu_904_p2");
    sc_trace(mVcdFile, ret_V_61_fu_981_p2, "ret_V_61_fu_981_p2");
    sc_trace(mVcdFile, add_ln209_16_fu_993_p2, "add_ln209_16_fu_993_p2");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
#endif

    }
}

sha256_transform::~sha256_transform() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    delete K_V_U;
    delete m_V_U;
}

void sha256_transform::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read())) {
        lhs_V_20_reg_354 = a_V_2_fu_999_p2.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read())) {
        lhs_V_20_reg_354 = a_V_reg_1091.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read())) {
        lhs_V_reg_397 = e_V_2_fu_987_p2.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read())) {
        lhs_V_reg_397 = e_V_reg_1135.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        p_01115_0_reg_319 = ap_const_lv5_0;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        p_01115_0_reg_319 = add_ln700_reg_1023.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(icmp_ln887_fu_439_p2.read(), ap_const_lv1_1))) {
        p_01115_1_reg_331 = ap_const_lv7_10;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        p_01115_1_reg_331 = i_V_fu_699_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read())) {
        p_01115_2_reg_343 = i_V_2_reg_1172.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read())) {
        p_01115_2_reg_343 = ap_const_lv7_0;
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read())) {
        p_01439_0_reg_429 = rhs_V_32_reg_418.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read())) {
        p_01439_0_reg_429 = state_V_q1.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read())) {
        p_01587_0_reg_386 = rhs_V_34_reg_375.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read())) {
        p_01587_0_reg_386 = d_V_reg_1119.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        p_0262_0_reg_308 = ap_const_lv7_0;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        p_0262_0_reg_308 = j_V_reg_1033.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read())) {
        rhs_V_32_reg_418 = rhs_V_reg_407.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read())) {
        rhs_V_32_reg_418 = state_V_q0.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read())) {
        rhs_V_33_reg_364 = lhs_V_20_reg_354.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read())) {
        rhs_V_33_reg_364 = b_V_reg_1097.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read())) {
        rhs_V_34_reg_375 = rhs_V_33_reg_364.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read())) {
        rhs_V_34_reg_375 = c_V_reg_1113.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read())) {
        rhs_V_reg_407 = lhs_V_reg_397.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read())) {
        rhs_V_reg_407 = f_V_reg_1141.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        a_V_reg_1091 = state_V_q0.read();
        b_V_reg_1097 = state_V_q1.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln887_1_fu_705_p2.read()))) {
        add_ln209_13_reg_1187 = add_ln209_13_fu_831_p2.read();
        ret_V_64_reg_1192 = ret_V_64_fu_855_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read()) && esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln887_1_fu_705_p2.read()))) {
        add_ln700_10_reg_1217 = add_ln700_10_fu_893_p2.read();
        add_ln700_5_reg_1197 = add_ln700_5_fu_873_p2.read();
        add_ln700_7_reg_1202 = add_ln700_7_fu_878_p2.read();
        add_ln700_8_reg_1207 = add_ln700_8_fu_883_p2.read();
        add_ln700_9_reg_1212 = add_ln700_9_fu_888_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        add_ln700_reg_1023 = add_ln700_fu_445_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read())) {
        c_V_reg_1113 = state_V_q0.read();
        d_V_reg_1119 = state_V_q1.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read())) {
        e_V_reg_1135 = state_V_q0.read();
        f_V_reg_1141 = state_V_q1.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read())) {
        g_V_reg_1157 = state_V_q0.read();
        h_V_reg_1163 = state_V_q1.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read())) {
        i_V_2_reg_1172 = i_V_2_fu_711_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(icmp_ln887_fu_439_p2.read(), ap_const_lv1_0))) {
        j_V_reg_1033 = j_V_fu_473_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        m_V_load_1_reg_1071 = m_V_q1.read();
        m_V_load_reg_1062 = m_V_q0.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln40_fu_489_p2.read()))) {
        trunc_ln215_2_reg_1041 = trunc_ln215_2_fu_495_p1.read();
    }
}

void sha256_transform::thread_K_V_address0() {
    K_V_address0 =  (sc_lv<6>) (zext_ln544_6_fu_819_p1.read());
}

void sha256_transform::thread_K_V_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read())) {
        K_V_ce0 = ap_const_logic_1;
    } else {
        K_V_ce0 = ap_const_logic_0;
    }
}

void sha256_transform::thread_a_V_2_fu_999_p2() {
    a_V_2_fu_999_p2 = (!add_ln209_16_fu_993_p2.read().is_01() || !ret_V_64_reg_1192.read().is_01())? sc_lv<32>(): (sc_biguint<32>(add_ln209_16_fu_993_p2.read()) + sc_biguint<32>(ret_V_64_reg_1192.read()));
}

void sha256_transform::thread_add_ln209_10_fu_686_p2() {
    add_ln209_10_fu_686_p2 = (!ret_V_44_fu_605_p2.read().is_01() || !ret_V_49_fu_675_p2.read().is_01())? sc_lv<32>(): (sc_biguint<32>(ret_V_44_fu_605_p2.read()) + sc_biguint<32>(ret_V_49_fu_675_p2.read()));
}

void sha256_transform::thread_add_ln209_11_fu_898_p2() {
    add_ln209_11_fu_898_p2 = (!K_V_q0.read().is_01() || !m_V_q0.read().is_01())? sc_lv<32>(): (sc_biguint<32>(K_V_q0.read()) + sc_biguint<32>(m_V_q0.read()));
}

void sha256_transform::thread_add_ln209_12_fu_825_p2() {
    add_ln209_12_fu_825_p2 = (!ret_V_57_fu_813_p2.read().is_01() || !ret_V_54_fu_789_p2.read().is_01())? sc_lv<32>(): (sc_biguint<32>(ret_V_57_fu_813_p2.read()) + sc_biguint<32>(ret_V_54_fu_789_p2.read()));
}

void sha256_transform::thread_add_ln209_13_fu_831_p2() {
    add_ln209_13_fu_831_p2 = (!add_ln209_12_fu_825_p2.read().is_01() || !p_01439_0_reg_429.read().is_01())? sc_lv<32>(): (sc_biguint<32>(add_ln209_12_fu_825_p2.read()) + sc_biguint<32>(p_01439_0_reg_429.read()));
}

void sha256_transform::thread_add_ln209_16_fu_993_p2() {
    add_ln209_16_fu_993_p2 = (!ret_V_61_fu_981_p2.read().is_01() || !t1_V_fu_904_p2.read().is_01())? sc_lv<32>(): (sc_biguint<32>(ret_V_61_fu_981_p2.read()) + sc_biguint<32>(t1_V_fu_904_p2.read()));
}

void sha256_transform::thread_add_ln209_fu_681_p2() {
    add_ln209_fu_681_p2 = (!m_V_load_1_reg_1071.read().is_01() || !m_V_q0.read().is_01())? sc_lv<32>(): (sc_biguint<32>(m_V_load_1_reg_1071.read()) + sc_biguint<32>(m_V_q0.read()));
}

void sha256_transform::thread_add_ln700_10_fu_893_p2() {
    add_ln700_10_fu_893_p2 = (!h_V_reg_1163.read().is_01() || !p_01439_0_reg_429.read().is_01())? sc_lv<32>(): (sc_biguint<32>(h_V_reg_1163.read()) + sc_biguint<32>(p_01439_0_reg_429.read()));
}

void sha256_transform::thread_add_ln700_3_fu_861_p2() {
    add_ln700_3_fu_861_p2 = (!a_V_reg_1091.read().is_01() || !lhs_V_20_reg_354.read().is_01())? sc_lv<32>(): (sc_biguint<32>(a_V_reg_1091.read()) + sc_biguint<32>(lhs_V_20_reg_354.read()));
}

void sha256_transform::thread_add_ln700_4_fu_867_p2() {
    add_ln700_4_fu_867_p2 = (!b_V_reg_1097.read().is_01() || !rhs_V_33_reg_364.read().is_01())? sc_lv<32>(): (sc_biguint<32>(b_V_reg_1097.read()) + sc_biguint<32>(rhs_V_33_reg_364.read()));
}

void sha256_transform::thread_add_ln700_5_fu_873_p2() {
    add_ln700_5_fu_873_p2 = (!c_V_reg_1113.read().is_01() || !rhs_V_34_reg_375.read().is_01())? sc_lv<32>(): (sc_biguint<32>(c_V_reg_1113.read()) + sc_biguint<32>(rhs_V_34_reg_375.read()));
}

void sha256_transform::thread_add_ln700_6_fu_1004_p2() {
    add_ln700_6_fu_1004_p2 = (!d_V_reg_1119.read().is_01() || !p_01587_0_reg_386.read().is_01())? sc_lv<32>(): (sc_biguint<32>(d_V_reg_1119.read()) + sc_biguint<32>(p_01587_0_reg_386.read()));
}

void sha256_transform::thread_add_ln700_7_fu_878_p2() {
    add_ln700_7_fu_878_p2 = (!e_V_reg_1135.read().is_01() || !lhs_V_reg_397.read().is_01())? sc_lv<32>(): (sc_biguint<32>(e_V_reg_1135.read()) + sc_biguint<32>(lhs_V_reg_397.read()));
}

void sha256_transform::thread_add_ln700_8_fu_883_p2() {
    add_ln700_8_fu_883_p2 = (!f_V_reg_1141.read().is_01() || !rhs_V_reg_407.read().is_01())? sc_lv<32>(): (sc_biguint<32>(f_V_reg_1141.read()) + sc_biguint<32>(rhs_V_reg_407.read()));
}

void sha256_transform::thread_add_ln700_9_fu_888_p2() {
    add_ln700_9_fu_888_p2 = (!g_V_reg_1157.read().is_01() || !rhs_V_32_reg_418.read().is_01())? sc_lv<32>(): (sc_biguint<32>(g_V_reg_1157.read()) + sc_biguint<32>(rhs_V_32_reg_418.read()));
}

void sha256_transform::thread_add_ln700_fu_445_p2() {
    add_ln700_fu_445_p2 = (!p_01115_0_reg_319.read().is_01() || !ap_const_lv5_1.is_01())? sc_lv<5>(): (sc_biguint<5>(p_01115_0_reg_319.read()) + sc_biguint<5>(ap_const_lv5_1));
}

void sha256_transform::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void sha256_transform::thread_ap_CS_fsm_state10() {
    ap_CS_fsm_state10 = ap_CS_fsm.read()[9];
}

void sha256_transform::thread_ap_CS_fsm_state11() {
    ap_CS_fsm_state11 = ap_CS_fsm.read()[10];
}

void sha256_transform::thread_ap_CS_fsm_state12() {
    ap_CS_fsm_state12 = ap_CS_fsm.read()[11];
}

void sha256_transform::thread_ap_CS_fsm_state13() {
    ap_CS_fsm_state13 = ap_CS_fsm.read()[12];
}

void sha256_transform::thread_ap_CS_fsm_state14() {
    ap_CS_fsm_state14 = ap_CS_fsm.read()[13];
}

void sha256_transform::thread_ap_CS_fsm_state15() {
    ap_CS_fsm_state15 = ap_CS_fsm.read()[14];
}

void sha256_transform::thread_ap_CS_fsm_state2() {
    ap_CS_fsm_state2 = ap_CS_fsm.read()[1];
}

void sha256_transform::thread_ap_CS_fsm_state3() {
    ap_CS_fsm_state3 = ap_CS_fsm.read()[2];
}

void sha256_transform::thread_ap_CS_fsm_state4() {
    ap_CS_fsm_state4 = ap_CS_fsm.read()[3];
}

void sha256_transform::thread_ap_CS_fsm_state5() {
    ap_CS_fsm_state5 = ap_CS_fsm.read()[4];
}

void sha256_transform::thread_ap_CS_fsm_state6() {
    ap_CS_fsm_state6 = ap_CS_fsm.read()[5];
}

void sha256_transform::thread_ap_CS_fsm_state7() {
    ap_CS_fsm_state7 = ap_CS_fsm.read()[6];
}

void sha256_transform::thread_ap_CS_fsm_state8() {
    ap_CS_fsm_state8 = ap_CS_fsm.read()[7];
}

void sha256_transform::thread_ap_CS_fsm_state9() {
    ap_CS_fsm_state9 = ap_CS_fsm.read()[8];
}

void sha256_transform::thread_ap_done() {
    if (((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read())) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state15.read()))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void sha256_transform::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void sha256_transform::thread_ap_ready() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state15.read())) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void sha256_transform::thread_data_V_address0() {
    data_V_address0 =  (sc_lv<7>) (zext_ln1356_fu_468_p1.read());
}

void sha256_transform::thread_data_V_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        data_V_ce0 = ap_const_logic_1;
    } else {
        data_V_ce0 = ap_const_logic_0;
    }
}

void sha256_transform::thread_e_V_2_fu_987_p2() {
    e_V_2_fu_987_p2 = (!t1_V_fu_904_p2.read().is_01() || !p_01587_0_reg_386.read().is_01())? sc_lv<32>(): (sc_biguint<32>(t1_V_fu_904_p2.read()) + sc_biguint<32>(p_01587_0_reg_386.read()));
}

void sha256_transform::thread_i_V_2_fu_711_p2() {
    i_V_2_fu_711_p2 = (!p_01115_2_reg_343.read().is_01() || !ap_const_lv7_1.is_01())? sc_lv<7>(): (sc_biguint<7>(p_01115_2_reg_343.read()) + sc_biguint<7>(ap_const_lv7_1));
}

void sha256_transform::thread_i_V_fu_699_p2() {
    i_V_fu_699_p2 = (!ap_const_lv7_1.is_01() || !p_01115_1_reg_331.read().is_01())? sc_lv<7>(): (sc_biguint<7>(ap_const_lv7_1) + sc_biguint<7>(p_01115_1_reg_331.read()));
}

void sha256_transform::thread_icmp_ln40_fu_489_p2() {
    icmp_ln40_fu_489_p2 = (!p_01115_1_reg_331.read().is_01() || !ap_const_lv7_40.is_01())? sc_lv<1>(): sc_lv<1>(p_01115_1_reg_331.read() == ap_const_lv7_40);
}

void sha256_transform::thread_icmp_ln887_1_fu_705_p2() {
    icmp_ln887_1_fu_705_p2 = (!p_01115_2_reg_343.read().is_01() || !ap_const_lv7_40.is_01())? sc_lv<1>(): sc_lv<1>(p_01115_2_reg_343.read() == ap_const_lv7_40);
}

void sha256_transform::thread_icmp_ln887_fu_439_p2() {
    icmp_ln887_fu_439_p2 = (!p_01115_0_reg_319.read().is_01() || !ap_const_lv5_10.is_01())? sc_lv<1>(): sc_lv<1>(p_01115_0_reg_319.read() == ap_const_lv5_10);
}

void sha256_transform::thread_j_V_fu_473_p2() {
    j_V_fu_473_p2 = (!ap_const_lv7_4.is_01() || !p_0262_0_reg_308.read().is_01())? sc_lv<7>(): (sc_biguint<7>(ap_const_lv7_4) + sc_biguint<7>(p_0262_0_reg_308.read()));
}

void sha256_transform::thread_m_V_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read())) {
        m_V_address0 =  (sc_lv<6>) (zext_ln544_6_fu_819_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        m_V_address0 =  (sc_lv<6>) (zext_ln544_11_fu_536_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        m_V_address0 =  (sc_lv<6>) (zext_ln544_8_fu_505_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        m_V_address0 =  (sc_lv<6>) (zext_ln544_fu_479_p1.read());
    } else {
        m_V_address0 = "XXXXXX";
    }
}

void sha256_transform::thread_m_V_address1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        m_V_address1 =  (sc_lv<6>) (zext_ln544_5_fu_541_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        m_V_address1 =  (sc_lv<6>) (zext_ln544_10_fu_526_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        m_V_address1 =  (sc_lv<6>) (zext_ln544_9_fu_516_p1.read());
    } else {
        m_V_address1 = "XXXXXX";
    }
}

void sha256_transform::thread_m_V_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()))) {
        m_V_ce0 = ap_const_logic_1;
    } else {
        m_V_ce0 = ap_const_logic_0;
    }
}

void sha256_transform::thread_m_V_ce1() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()))) {
        m_V_ce1 = ap_const_logic_1;
    } else {
        m_V_ce1 = ap_const_logic_0;
    }
}

void sha256_transform::thread_m_V_d0() {
    m_V_d0 = esl_zext<32,8>(data_V_q0.read());
}

void sha256_transform::thread_m_V_d1() {
    m_V_d1 = (!add_ln209_10_fu_686_p2.read().is_01() || !add_ln209_fu_681_p2.read().is_01())? sc_lv<32>(): (sc_biguint<32>(add_ln209_10_fu_686_p2.read()) + sc_biguint<32>(add_ln209_fu_681_p2.read()));
}

void sha256_transform::thread_m_V_we0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        m_V_we0 = ap_const_logic_1;
    } else {
        m_V_we0 = ap_const_logic_0;
    }
}

void sha256_transform::thread_m_V_we1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        m_V_we1 = ap_const_logic_1;
    } else {
        m_V_we1 = ap_const_logic_0;
    }
}

void sha256_transform::thread_r_V_11_fu_586_p4() {
    r_V_11_fu_586_p4 = m_V_load_reg_1062.read().range(31, 10);
}

void sha256_transform::thread_r_V_12_fu_611_p4() {
    r_V_12_fu_611_p4 = m_V_q1.read().range(31, 7);
}

void sha256_transform::thread_r_V_13_fu_633_p4() {
    r_V_13_fu_633_p4 = m_V_q1.read().range(31, 18);
}

void sha256_transform::thread_r_V_14_fu_655_p4() {
    r_V_14_fu_655_p4 = m_V_q1.read().range(31, 3);
}

void sha256_transform::thread_r_V_15_fu_717_p4() {
    r_V_15_fu_717_p4 = lhs_V_reg_397.read().range(31, 6);
}

void sha256_transform::thread_r_V_16_fu_739_p4() {
    r_V_16_fu_739_p4 = lhs_V_reg_397.read().range(31, 11);
}

void sha256_transform::thread_r_V_17_fu_761_p4() {
    r_V_17_fu_761_p4 = lhs_V_reg_397.read().range(31, 25);
}

void sha256_transform::thread_r_V_18_fu_909_p4() {
    r_V_18_fu_909_p4 = lhs_V_20_reg_354.read().range(31, 2);
}

void sha256_transform::thread_r_V_19_fu_931_p4() {
    r_V_19_fu_931_p4 = lhs_V_20_reg_354.read().range(31, 13);
}

void sha256_transform::thread_r_V_20_fu_953_p4() {
    r_V_20_fu_953_p4 = lhs_V_20_reg_354.read().range(31, 22);
}

void sha256_transform::thread_r_V_24_fu_595_p1() {
    r_V_24_fu_595_p1 = esl_zext<32,22>(r_V_11_fu_586_p4.read());
}

void sha256_transform::thread_r_V_25_fu_665_p1() {
    r_V_25_fu_665_p1 = esl_zext<32,29>(r_V_14_fu_655_p4.read());
}

void sha256_transform::thread_r_V_26_fu_801_p2() {
    r_V_26_fu_801_p2 = (lhs_V_reg_397.read() ^ ap_const_lv32_FFFFFFFF);
}

void sha256_transform::thread_r_V_fu_546_p4() {
    r_V_fu_546_p4 = m_V_load_reg_1062.read().range(31, 17);
}

void sha256_transform::thread_r_V_s_fu_566_p4() {
    r_V_s_fu_566_p4 = m_V_load_reg_1062.read().range(31, 19);
}

void sha256_transform::thread_ret_V_41_fu_499_p2() {
    ret_V_41_fu_499_p2 = (!ap_const_lv6_3E.is_01() || !trunc_ln215_2_fu_495_p1.read().is_01())? sc_lv<6>(): (sc_bigint<6>(ap_const_lv6_3E) + sc_biguint<6>(trunc_ln215_2_fu_495_p1.read()));
}

void sha256_transform::thread_ret_V_44_fu_605_p2() {
    ret_V_44_fu_605_p2 = (xor_ln1357_fu_599_p2.read() ^ ret_V_65_fu_558_p3.read());
}

void sha256_transform::thread_ret_V_45_fu_510_p2() {
    ret_V_45_fu_510_p2 = (!ap_const_lv6_39.is_01() || !trunc_ln215_2_fu_495_p1.read().is_01())? sc_lv<6>(): (sc_bigint<6>(ap_const_lv6_39) + sc_biguint<6>(trunc_ln215_2_fu_495_p1.read()));
}

void sha256_transform::thread_ret_V_46_fu_521_p2() {
    ret_V_46_fu_521_p2 = (!ap_const_lv6_31.is_01() || !trunc_ln215_2_reg_1041.read().is_01())? sc_lv<6>(): (sc_bigint<6>(ap_const_lv6_31) + sc_biguint<6>(trunc_ln215_2_reg_1041.read()));
}

void sha256_transform::thread_ret_V_49_fu_675_p2() {
    ret_V_49_fu_675_p2 = (xor_ln1357_12_fu_669_p2.read() ^ ret_V_67_fu_625_p3.read());
}

void sha256_transform::thread_ret_V_50_fu_531_p2() {
    ret_V_50_fu_531_p2 = (!ap_const_lv6_30.is_01() || !trunc_ln215_2_reg_1041.read().is_01())? sc_lv<6>(): (sc_bigint<6>(ap_const_lv6_30) + sc_biguint<6>(trunc_ln215_2_reg_1041.read()));
}

void sha256_transform::thread_ret_V_54_fu_789_p2() {
    ret_V_54_fu_789_p2 = (xor_ln1357_14_fu_783_p2.read() ^ ret_V_71_fu_775_p3.read());
}

void sha256_transform::thread_ret_V_57_fu_813_p2() {
    ret_V_57_fu_813_p2 = (ret_V_73_fu_807_p2.read() ^ ret_V_72_fu_795_p2.read());
}

void sha256_transform::thread_ret_V_61_fu_981_p2() {
    ret_V_61_fu_981_p2 = (xor_ln1357_17_fu_975_p2.read() ^ ret_V_76_fu_967_p3.read());
}

void sha256_transform::thread_ret_V_64_fu_855_p2() {
    ret_V_64_fu_855_p2 = (ret_V_77_fu_843_p2.read() ^ ret_V_78_fu_849_p2.read());
}

void sha256_transform::thread_ret_V_65_fu_558_p3() {
    ret_V_65_fu_558_p3 = esl_concat<17,15>(trunc_ln1503_fu_555_p1.read(), r_V_fu_546_p4.read());
}

void sha256_transform::thread_ret_V_66_fu_578_p3() {
    ret_V_66_fu_578_p3 = esl_concat<19,13>(trunc_ln1503_10_fu_575_p1.read(), r_V_s_fu_566_p4.read());
}

void sha256_transform::thread_ret_V_67_fu_625_p3() {
    ret_V_67_fu_625_p3 = esl_concat<7,25>(trunc_ln1503_11_fu_621_p1.read(), r_V_12_fu_611_p4.read());
}

void sha256_transform::thread_ret_V_68_fu_647_p3() {
    ret_V_68_fu_647_p3 = esl_concat<18,14>(trunc_ln1503_12_fu_643_p1.read(), r_V_13_fu_633_p4.read());
}

void sha256_transform::thread_ret_V_69_fu_731_p3() {
    ret_V_69_fu_731_p3 = esl_concat<6,26>(trunc_ln1503_13_fu_727_p1.read(), r_V_15_fu_717_p4.read());
}

void sha256_transform::thread_ret_V_70_fu_753_p3() {
    ret_V_70_fu_753_p3 = esl_concat<11,21>(trunc_ln1503_14_fu_749_p1.read(), r_V_16_fu_739_p4.read());
}

void sha256_transform::thread_ret_V_71_fu_775_p3() {
    ret_V_71_fu_775_p3 = esl_concat<25,7>(trunc_ln1503_15_fu_771_p1.read(), r_V_17_fu_761_p4.read());
}

void sha256_transform::thread_ret_V_72_fu_795_p2() {
    ret_V_72_fu_795_p2 = (rhs_V_reg_407.read() & lhs_V_reg_397.read());
}

void sha256_transform::thread_ret_V_73_fu_807_p2() {
    ret_V_73_fu_807_p2 = (rhs_V_32_reg_418.read() & r_V_26_fu_801_p2.read());
}

void sha256_transform::thread_ret_V_74_fu_923_p3() {
    ret_V_74_fu_923_p3 = esl_concat<2,30>(trunc_ln1503_16_fu_919_p1.read(), r_V_18_fu_909_p4.read());
}

void sha256_transform::thread_ret_V_75_fu_945_p3() {
    ret_V_75_fu_945_p3 = esl_concat<13,19>(trunc_ln1503_17_fu_941_p1.read(), r_V_19_fu_931_p4.read());
}

void sha256_transform::thread_ret_V_76_fu_967_p3() {
    ret_V_76_fu_967_p3 = esl_concat<22,10>(trunc_ln1503_18_fu_963_p1.read(), r_V_20_fu_953_p4.read());
}

void sha256_transform::thread_ret_V_77_fu_843_p2() {
    ret_V_77_fu_843_p2 = (xor_ln1357_9_fu_837_p2.read() & lhs_V_20_reg_354.read());
}

void sha256_transform::thread_ret_V_78_fu_849_p2() {
    ret_V_78_fu_849_p2 = (rhs_V_34_reg_375.read() & rhs_V_33_reg_364.read());
}

void sha256_transform::thread_ret_V_fu_455_p2() {
    ret_V_fu_455_p2 = (trunc_ln215_fu_451_p1.read() | ap_const_lv6_3);
}

void sha256_transform::thread_state_V_addr_10_reg_1108() {
    state_V_addr_10_reg_1108 =  (sc_lv<3>) (ap_const_lv64_3);
}

void sha256_transform::thread_state_V_addr_11_reg_1125() {
    state_V_addr_11_reg_1125 =  (sc_lv<3>) (ap_const_lv64_4);
}

void sha256_transform::thread_state_V_addr_12_reg_1130() {
    state_V_addr_12_reg_1130 =  (sc_lv<3>) (ap_const_lv64_5);
}

void sha256_transform::thread_state_V_addr_13_reg_1147() {
    state_V_addr_13_reg_1147 =  (sc_lv<3>) (ap_const_lv64_6);
}

void sha256_transform::thread_state_V_addr_14_reg_1152() {
    state_V_addr_14_reg_1152 =  (sc_lv<3>) (ap_const_lv64_7);
}

void sha256_transform::thread_state_V_addr_8_reg_1057() {
    state_V_addr_8_reg_1057 =  (sc_lv<3>) (ap_const_lv64_1);
}

void sha256_transform::thread_state_V_addr_9_reg_1103() {
    state_V_addr_9_reg_1103 =  (sc_lv<3>) (ap_const_lv64_2);
}

void sha256_transform::thread_state_V_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state15.read())) {
        state_V_address0 = state_V_addr_13_reg_1147.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state14.read())) {
        state_V_address0 = state_V_addr_11_reg_1125.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read())) {
        state_V_address0 = state_V_addr_9_reg_1103.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read())) {
        state_V_address0 =  (sc_lv<3>) (ap_const_lv64_6);
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read())) {
        state_V_address0 =  (sc_lv<3>) (ap_const_lv64_4);
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        state_V_address0 =  (sc_lv<3>) (ap_const_lv64_2);
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) || 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read()))) {
        state_V_address0 =  (sc_lv<3>) (ap_const_lv64_0);
    } else {
        state_V_address0 =  (sc_lv<3>) ("XXX");
    }
}

void sha256_transform::thread_state_V_address1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state15.read())) {
        state_V_address1 = state_V_addr_14_reg_1152.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state14.read())) {
        state_V_address1 = state_V_addr_12_reg_1130.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read())) {
        state_V_address1 = state_V_addr_10_reg_1108.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read())) {
        state_V_address1 = state_V_addr_8_reg_1057.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read())) {
        state_V_address1 =  (sc_lv<3>) (ap_const_lv64_7);
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read())) {
        state_V_address1 =  (sc_lv<3>) (ap_const_lv64_5);
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        state_V_address1 =  (sc_lv<3>) (ap_const_lv64_3);
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        state_V_address1 =  (sc_lv<3>) (ap_const_lv64_1);
    } else {
        state_V_address1 =  (sc_lv<3>) ("XXX");
    }
}

void sha256_transform::thread_state_V_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state14.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state15.read()))) {
        state_V_ce0 = ap_const_logic_1;
    } else {
        state_V_ce0 = ap_const_logic_0;
    }
}

void sha256_transform::thread_state_V_ce1() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state14.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state15.read()))) {
        state_V_ce1 = ap_const_logic_1;
    } else {
        state_V_ce1 = ap_const_logic_0;
    }
}

void sha256_transform::thread_state_V_d0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state15.read())) {
        state_V_d0 = add_ln700_9_reg_1212.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state14.read())) {
        state_V_d0 = add_ln700_7_reg_1202.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read())) {
        state_V_d0 = add_ln700_5_reg_1197.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read())) {
        state_V_d0 = add_ln700_3_fu_861_p2.read();
    } else {
        state_V_d0 =  (sc_lv<32>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
    }
}

void sha256_transform::thread_state_V_d1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state15.read())) {
        state_V_d1 = add_ln700_10_reg_1217.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state14.read())) {
        state_V_d1 = add_ln700_8_reg_1207.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read())) {
        state_V_d1 = add_ln700_6_fu_1004_p2.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read())) {
        state_V_d1 = add_ln700_4_fu_867_p2.read();
    } else {
        state_V_d1 =  (sc_lv<32>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
    }
}

void sha256_transform::thread_state_V_we0() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln887_1_fu_705_p2.read())) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state14.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state15.read()))) {
        state_V_we0 = ap_const_logic_1;
    } else {
        state_V_we0 = ap_const_logic_0;
    }
}

void sha256_transform::thread_state_V_we1() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln887_1_fu_705_p2.read())) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state14.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state15.read()))) {
        state_V_we1 = ap_const_logic_1;
    } else {
        state_V_we1 = ap_const_logic_0;
    }
}

void sha256_transform::thread_t1_V_fu_904_p2() {
    t1_V_fu_904_p2 = (!add_ln209_13_reg_1187.read().is_01() || !add_ln209_11_fu_898_p2.read().is_01())? sc_lv<32>(): (sc_biguint<32>(add_ln209_13_reg_1187.read()) + sc_biguint<32>(add_ln209_11_fu_898_p2.read()));
}

void sha256_transform::thread_tmp_fu_461_p3() {
    tmp_fu_461_p3 = esl_concat<1,6>(data_V_offset.read(), ret_V_fu_455_p2.read());
}

void sha256_transform::thread_trunc_ln1503_10_fu_575_p1() {
    trunc_ln1503_10_fu_575_p1 = m_V_load_reg_1062.read().range(19-1, 0);
}

void sha256_transform::thread_trunc_ln1503_11_fu_621_p1() {
    trunc_ln1503_11_fu_621_p1 = m_V_q1.read().range(7-1, 0);
}

void sha256_transform::thread_trunc_ln1503_12_fu_643_p1() {
    trunc_ln1503_12_fu_643_p1 = m_V_q1.read().range(18-1, 0);
}

void sha256_transform::thread_trunc_ln1503_13_fu_727_p1() {
    trunc_ln1503_13_fu_727_p1 = lhs_V_reg_397.read().range(6-1, 0);
}

void sha256_transform::thread_trunc_ln1503_14_fu_749_p1() {
    trunc_ln1503_14_fu_749_p1 = lhs_V_reg_397.read().range(11-1, 0);
}

void sha256_transform::thread_trunc_ln1503_15_fu_771_p1() {
    trunc_ln1503_15_fu_771_p1 = lhs_V_reg_397.read().range(25-1, 0);
}

void sha256_transform::thread_trunc_ln1503_16_fu_919_p1() {
    trunc_ln1503_16_fu_919_p1 = lhs_V_20_reg_354.read().range(2-1, 0);
}

void sha256_transform::thread_trunc_ln1503_17_fu_941_p1() {
    trunc_ln1503_17_fu_941_p1 = lhs_V_20_reg_354.read().range(13-1, 0);
}

void sha256_transform::thread_trunc_ln1503_18_fu_963_p1() {
    trunc_ln1503_18_fu_963_p1 = lhs_V_20_reg_354.read().range(22-1, 0);
}

void sha256_transform::thread_trunc_ln1503_fu_555_p1() {
    trunc_ln1503_fu_555_p1 = m_V_load_reg_1062.read().range(17-1, 0);
}

void sha256_transform::thread_trunc_ln215_2_fu_495_p1() {
    trunc_ln215_2_fu_495_p1 = p_01115_1_reg_331.read().range(6-1, 0);
}

void sha256_transform::thread_trunc_ln215_fu_451_p1() {
    trunc_ln215_fu_451_p1 = p_0262_0_reg_308.read().range(6-1, 0);
}

void sha256_transform::thread_xor_ln1357_12_fu_669_p2() {
    xor_ln1357_12_fu_669_p2 = (r_V_25_fu_665_p1.read() ^ ret_V_68_fu_647_p3.read());
}

void sha256_transform::thread_xor_ln1357_14_fu_783_p2() {
    xor_ln1357_14_fu_783_p2 = (ret_V_69_fu_731_p3.read() ^ ret_V_70_fu_753_p3.read());
}

void sha256_transform::thread_xor_ln1357_17_fu_975_p2() {
    xor_ln1357_17_fu_975_p2 = (ret_V_74_fu_923_p3.read() ^ ret_V_75_fu_945_p3.read());
}

void sha256_transform::thread_xor_ln1357_9_fu_837_p2() {
    xor_ln1357_9_fu_837_p2 = (rhs_V_34_reg_375.read() ^ rhs_V_33_reg_364.read());
}

void sha256_transform::thread_xor_ln1357_fu_599_p2() {
    xor_ln1357_fu_599_p2 = (r_V_24_fu_595_p1.read() ^ ret_V_66_fu_578_p3.read());
}

void sha256_transform::thread_zext_ln1356_fu_468_p1() {
    zext_ln1356_fu_468_p1 = esl_zext<64,7>(tmp_fu_461_p3.read());
}

void sha256_transform::thread_zext_ln544_10_fu_526_p1() {
    zext_ln544_10_fu_526_p1 = esl_zext<64,6>(ret_V_46_fu_521_p2.read());
}

void sha256_transform::thread_zext_ln544_11_fu_536_p1() {
    zext_ln544_11_fu_536_p1 = esl_zext<64,6>(ret_V_50_fu_531_p2.read());
}

void sha256_transform::thread_zext_ln544_5_fu_541_p1() {
    zext_ln544_5_fu_541_p1 = esl_zext<64,7>(p_01115_1_reg_331.read());
}

void sha256_transform::thread_zext_ln544_6_fu_819_p1() {
    zext_ln544_6_fu_819_p1 = esl_zext<64,7>(p_01115_2_reg_343.read());
}

void sha256_transform::thread_zext_ln544_8_fu_505_p1() {
    zext_ln544_8_fu_505_p1 = esl_zext<64,6>(ret_V_41_fu_499_p2.read());
}

void sha256_transform::thread_zext_ln544_9_fu_516_p1() {
    zext_ln544_9_fu_516_p1 = esl_zext<64,6>(ret_V_45_fu_510_p2.read());
}

void sha256_transform::thread_zext_ln544_fu_479_p1() {
    zext_ln544_fu_479_p1 = esl_zext<64,5>(p_01115_0_reg_319.read());
}

void sha256_transform::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(icmp_ln887_fu_439_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state4;
            } else {
                ap_NS_fsm = ap_ST_fsm_state3;
            }
            break;
        case 4 : 
            ap_NS_fsm = ap_ST_fsm_state2;
            break;
        case 8 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && esl_seteq<1,1,1>(icmp_ln40_fu_489_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state7;
            } else {
                ap_NS_fsm = ap_ST_fsm_state5;
            }
            break;
        case 16 : 
            ap_NS_fsm = ap_ST_fsm_state6;
            break;
        case 32 : 
            ap_NS_fsm = ap_ST_fsm_state4;
            break;
        case 64 : 
            ap_NS_fsm = ap_ST_fsm_state8;
            break;
        case 128 : 
            ap_NS_fsm = ap_ST_fsm_state9;
            break;
        case 256 : 
            ap_NS_fsm = ap_ST_fsm_state10;
            break;
        case 512 : 
            ap_NS_fsm = ap_ST_fsm_state11;
            break;
        case 1024 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read()) && esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln887_1_fu_705_p2.read()))) {
                ap_NS_fsm = ap_ST_fsm_state13;
            } else {
                ap_NS_fsm = ap_ST_fsm_state12;
            }
            break;
        case 2048 : 
            ap_NS_fsm = ap_ST_fsm_state11;
            break;
        case 4096 : 
            ap_NS_fsm = ap_ST_fsm_state14;
            break;
        case 8192 : 
            ap_NS_fsm = ap_ST_fsm_state15;
            break;
        case 16384 : 
            ap_NS_fsm = ap_ST_fsm_state1;
            break;
        default : 
            ap_NS_fsm =  (sc_lv<15>) ("XXXXXXXXXXXXXXX");
            break;
    }
}

}

