# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/comp4601/deliver/Vivado/baseDesign_stream/baseline_hls.srcs/sources_1/bd/design_4/ip/design_4_sha256d_0_0/design_4_sha256d_0_0.xci
# IP: The module: 'design_4_sha256d_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/comp4601/deliver/Vivado/baseDesign_stream/baseline_hls.gen/sources_1/bd/design_4/ip/design_4_sha256d_0_0/constraints/sha256d_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_4_sha256d_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: C:/comp4601/deliver/Vivado/baseDesign_stream/baseline_hls.srcs/sources_1/bd/design_4/ip/design_4_sha256d_0_0/design_4_sha256d_0_0.xci
# IP: The module: 'design_4_sha256d_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/comp4601/deliver/Vivado/baseDesign_stream/baseline_hls.gen/sources_1/bd/design_4/ip/design_4_sha256d_0_0/constraints/sha256d_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_4_sha256d_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
