// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2020.1
// Copyright (C) 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="sha256d,hls_ip_2020_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=1,HLS_INPUT_PART=xqzu5ev-ffrb900-1-i,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=4.796000,HLS_SYN_LAT=1698,HLS_SYN_TPT=none,HLS_SYN_MEM=12,HLS_SYN_DSP=0,HLS_SYN_FF=2000,HLS_SYN_LUT=4774,HLS_VERSION=2020_1}" *)

module sha256d (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        input_V_address0,
        input_V_ce0,
        input_V_q0,
        output_V_address0,
        output_V_ce0,
        output_V_we0,
        output_V_d0
);

parameter    ap_ST_fsm_state1 = 17'd1;
parameter    ap_ST_fsm_state2 = 17'd2;
parameter    ap_ST_fsm_state3 = 17'd4;
parameter    ap_ST_fsm_state4 = 17'd8;
parameter    ap_ST_fsm_state5 = 17'd16;
parameter    ap_ST_fsm_state6 = 17'd32;
parameter    ap_ST_fsm_state7 = 17'd64;
parameter    ap_ST_fsm_state8 = 17'd128;
parameter    ap_ST_fsm_state9 = 17'd256;
parameter    ap_ST_fsm_state10 = 17'd512;
parameter    ap_ST_fsm_state11 = 17'd1024;
parameter    ap_ST_fsm_state12 = 17'd2048;
parameter    ap_ST_fsm_state13 = 17'd4096;
parameter    ap_ST_fsm_state14 = 17'd8192;
parameter    ap_ST_fsm_state15 = 17'd16384;
parameter    ap_ST_fsm_state16 = 17'd32768;
parameter    ap_ST_fsm_state17 = 17'd65536;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [6:0] input_V_address0;
output   input_V_ce0;
input  [7:0] input_V_q0;
output  [2:0] output_V_address0;
output   output_V_ce0;
output   output_V_we0;
output  [31:0] output_V_d0;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg output_V_ce0;
reg output_V_we0;

(* fsm_encoding = "none" *) reg   [16:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [3:0] i_fu_351_p2;
reg   [3:0] i_reg_382;
wire    ap_CS_fsm_state9;
wire   [63:0] zext_ln126_fu_357_p1;
reg   [63:0] zext_ln126_reg_387;
wire   [0:0] icmp_ln125_fu_345_p2;
wire   [3:0] i_1_fu_368_p2;
reg   [3:0] i_1_reg_400;
wire    ap_CS_fsm_state16;
wire   [63:0] zext_ln163_fu_374_p1;
reg   [63:0] zext_ln163_reg_405;
wire   [0:0] icmp_ln162_fu_362_p2;
reg   [2:0] hash1_V_2_address0;
reg    hash1_V_2_ce0;
reg    hash1_V_2_we0;
reg   [31:0] hash1_V_2_d0;
wire   [31:0] hash1_V_2_q0;
reg   [2:0] hash1_V_2_address1;
reg    hash1_V_2_ce1;
reg    hash1_V_2_we1;
reg   [31:0] hash1_V_2_d1;
wire   [31:0] hash1_V_2_q1;
reg   [5:0] data_V_1_address0;
reg    data_V_1_ce0;
reg    data_V_1_we0;
wire   [7:0] data_V_1_q0;
reg   [2:0] hash1_V_1_address0;
reg    hash1_V_1_ce0;
reg    hash1_V_1_we0;
reg   [31:0] hash1_V_1_d0;
wire   [31:0] hash1_V_1_q0;
reg   [2:0] hash1_V_1_address1;
reg    hash1_V_1_ce1;
reg    hash1_V_1_we1;
reg   [31:0] hash1_V_1_d1;
wire   [31:0] hash1_V_1_q1;
reg   [6:0] data_V_address0;
reg    data_V_ce0;
reg    data_V_we0;
wire   [7:0] data_V_q0;
reg   [2:0] hash1_V_address0;
reg    hash1_V_ce0;
reg    hash1_V_we0;
wire   [31:0] hash1_V_q0;
wire    grp_sha256_transform_fu_313_ap_start;
wire    grp_sha256_transform_fu_313_ap_done;
wire    grp_sha256_transform_fu_313_ap_idle;
wire    grp_sha256_transform_fu_313_ap_ready;
wire   [2:0] grp_sha256_transform_fu_313_state_V_address0;
wire    grp_sha256_transform_fu_313_state_V_ce0;
wire    grp_sha256_transform_fu_313_state_V_we0;
wire   [31:0] grp_sha256_transform_fu_313_state_V_d0;
wire   [2:0] grp_sha256_transform_fu_313_state_V_address1;
wire    grp_sha256_transform_fu_313_state_V_ce1;
wire    grp_sha256_transform_fu_313_state_V_we1;
wire   [31:0] grp_sha256_transform_fu_313_state_V_d1;
wire   [6:0] grp_sha256_transform_fu_313_data_V_address0;
wire    grp_sha256_transform_fu_313_data_V_ce0;
reg   [0:0] grp_sha256_transform_fu_313_data_V_offset;
wire    grp_sha256_transform_1_fu_324_ap_start;
wire    grp_sha256_transform_1_fu_324_ap_done;
wire    grp_sha256_transform_1_fu_324_ap_idle;
wire    grp_sha256_transform_1_fu_324_ap_ready;
wire   [2:0] grp_sha256_transform_1_fu_324_state_V_address0;
wire    grp_sha256_transform_1_fu_324_state_V_ce0;
wire    grp_sha256_transform_1_fu_324_state_V_we0;
wire   [31:0] grp_sha256_transform_1_fu_324_state_V_d0;
wire   [2:0] grp_sha256_transform_1_fu_324_state_V_address1;
wire    grp_sha256_transform_1_fu_324_state_V_ce1;
wire    grp_sha256_transform_1_fu_324_state_V_we1;
wire   [31:0] grp_sha256_transform_1_fu_324_state_V_d1;
wire   [5:0] grp_sha256_transform_1_fu_324_data_V_address0;
wire    grp_sha256_transform_1_fu_324_data_V_ce0;
wire    grp_sha256_prepare_1_fu_332_ap_start;
wire    grp_sha256_prepare_1_fu_332_ap_done;
wire    grp_sha256_prepare_1_fu_332_ap_idle;
wire    grp_sha256_prepare_1_fu_332_ap_ready;
wire   [6:0] grp_sha256_prepare_1_fu_332_input_V_address0;
wire    grp_sha256_prepare_1_fu_332_input_V_ce0;
wire   [6:0] grp_sha256_prepare_1_fu_332_data_V_address0;
wire    grp_sha256_prepare_1_fu_332_data_V_ce0;
wire    grp_sha256_prepare_1_fu_332_data_V_we0;
wire   [7:0] grp_sha256_prepare_1_fu_332_data_V_d0;
wire    grp_sha256_prepare_2_fu_339_ap_start;
wire    grp_sha256_prepare_2_fu_339_ap_done;
wire    grp_sha256_prepare_2_fu_339_ap_idle;
wire    grp_sha256_prepare_2_fu_339_ap_ready;
wire   [2:0] grp_sha256_prepare_2_fu_339_input_V_address0;
wire    grp_sha256_prepare_2_fu_339_input_V_ce0;
wire   [5:0] grp_sha256_prepare_2_fu_339_data_V_address0;
wire    grp_sha256_prepare_2_fu_339_data_V_ce0;
wire    grp_sha256_prepare_2_fu_339_data_V_we0;
wire   [7:0] grp_sha256_prepare_2_fu_339_data_V_d0;
reg   [3:0] i_0_i_reg_291;
wire    ap_CS_fsm_state8;
wire    ap_CS_fsm_state10;
reg   [3:0] i_0_i12_reg_302;
wire    ap_CS_fsm_state15;
wire    ap_CS_fsm_state17;
reg    grp_sha256_transform_fu_313_ap_start_reg;
wire    ap_CS_fsm_state5;
wire    ap_CS_fsm_state7;
wire    ap_CS_fsm_state6;
reg    grp_sha256_transform_1_fu_324_ap_start_reg;
wire    ap_CS_fsm_state14;
reg    grp_sha256_prepare_1_fu_332_ap_start_reg;
wire    ap_CS_fsm_state3;
wire    ap_CS_fsm_state4;
reg    grp_sha256_prepare_2_fu_339_ap_start_reg;
wire    ap_CS_fsm_state12;
wire    ap_CS_fsm_state13;
wire    ap_CS_fsm_state2;
wire    ap_CS_fsm_state11;
reg   [16:0] ap_NS_fsm;

// power-on initialization
initial begin
#0 ap_CS_fsm = 17'd1;
#0 grp_sha256_transform_fu_313_ap_start_reg = 1'b0;
#0 grp_sha256_transform_1_fu_324_ap_start_reg = 1'b0;
#0 grp_sha256_prepare_1_fu_332_ap_start_reg = 1'b0;
#0 grp_sha256_prepare_2_fu_339_ap_start_reg = 1'b0;
end

sha256d_hash1_V_2 #(
    .DataWidth( 32 ),
    .AddressRange( 8 ),
    .AddressWidth( 3 ))
hash1_V_2_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(hash1_V_2_address0),
    .ce0(hash1_V_2_ce0),
    .we0(hash1_V_2_we0),
    .d0(hash1_V_2_d0),
    .q0(hash1_V_2_q0),
    .address1(hash1_V_2_address1),
    .ce1(hash1_V_2_ce1),
    .we1(hash1_V_2_we1),
    .d1(hash1_V_2_d1),
    .q1(hash1_V_2_q1)
);

sha256_prepare_2_eOg #(
    .DataWidth( 8 ),
    .AddressRange( 64 ),
    .AddressWidth( 6 ))
data_V_1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(data_V_1_address0),
    .ce0(data_V_1_ce0),
    .we0(data_V_1_we0),
    .d0(grp_sha256_prepare_2_fu_339_data_V_d0),
    .q0(data_V_1_q0)
);

sha256d_hash1_V_2 #(
    .DataWidth( 32 ),
    .AddressRange( 8 ),
    .AddressWidth( 3 ))
hash1_V_1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(hash1_V_1_address0),
    .ce0(hash1_V_1_ce0),
    .we0(hash1_V_1_we0),
    .d0(hash1_V_1_d0),
    .q0(hash1_V_1_q0),
    .address1(hash1_V_1_address1),
    .ce1(hash1_V_1_ce1),
    .we1(hash1_V_1_we1),
    .d1(hash1_V_1_d1),
    .q1(hash1_V_1_q1)
);

sha256_prepare_1_bkb #(
    .DataWidth( 8 ),
    .AddressRange( 128 ),
    .AddressWidth( 7 ))
data_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(data_V_address0),
    .ce0(data_V_ce0),
    .we0(data_V_we0),
    .d0(grp_sha256_prepare_1_fu_332_data_V_d0),
    .q0(data_V_q0)
);

sha256d_hash1_V #(
    .DataWidth( 32 ),
    .AddressRange( 8 ),
    .AddressWidth( 3 ))
hash1_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(hash1_V_address0),
    .ce0(hash1_V_ce0),
    .we0(hash1_V_we0),
    .d0(hash1_V_1_q0),
    .q0(hash1_V_q0)
);

sha256_transform grp_sha256_transform_fu_313(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_sha256_transform_fu_313_ap_start),
    .ap_done(grp_sha256_transform_fu_313_ap_done),
    .ap_idle(grp_sha256_transform_fu_313_ap_idle),
    .ap_ready(grp_sha256_transform_fu_313_ap_ready),
    .state_V_address0(grp_sha256_transform_fu_313_state_V_address0),
    .state_V_ce0(grp_sha256_transform_fu_313_state_V_ce0),
    .state_V_we0(grp_sha256_transform_fu_313_state_V_we0),
    .state_V_d0(grp_sha256_transform_fu_313_state_V_d0),
    .state_V_q0(hash1_V_1_q0),
    .state_V_address1(grp_sha256_transform_fu_313_state_V_address1),
    .state_V_ce1(grp_sha256_transform_fu_313_state_V_ce1),
    .state_V_we1(grp_sha256_transform_fu_313_state_V_we1),
    .state_V_d1(grp_sha256_transform_fu_313_state_V_d1),
    .state_V_q1(hash1_V_1_q1),
    .data_V_address0(grp_sha256_transform_fu_313_data_V_address0),
    .data_V_ce0(grp_sha256_transform_fu_313_data_V_ce0),
    .data_V_q0(data_V_q0),
    .data_V_offset(grp_sha256_transform_fu_313_data_V_offset)
);

sha256_transform_1 grp_sha256_transform_1_fu_324(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_sha256_transform_1_fu_324_ap_start),
    .ap_done(grp_sha256_transform_1_fu_324_ap_done),
    .ap_idle(grp_sha256_transform_1_fu_324_ap_idle),
    .ap_ready(grp_sha256_transform_1_fu_324_ap_ready),
    .state_V_address0(grp_sha256_transform_1_fu_324_state_V_address0),
    .state_V_ce0(grp_sha256_transform_1_fu_324_state_V_ce0),
    .state_V_we0(grp_sha256_transform_1_fu_324_state_V_we0),
    .state_V_d0(grp_sha256_transform_1_fu_324_state_V_d0),
    .state_V_q0(hash1_V_2_q0),
    .state_V_address1(grp_sha256_transform_1_fu_324_state_V_address1),
    .state_V_ce1(grp_sha256_transform_1_fu_324_state_V_ce1),
    .state_V_we1(grp_sha256_transform_1_fu_324_state_V_we1),
    .state_V_d1(grp_sha256_transform_1_fu_324_state_V_d1),
    .state_V_q1(hash1_V_2_q1),
    .data_V_address0(grp_sha256_transform_1_fu_324_data_V_address0),
    .data_V_ce0(grp_sha256_transform_1_fu_324_data_V_ce0),
    .data_V_q0(data_V_1_q0)
);

sha256_prepare_1 grp_sha256_prepare_1_fu_332(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_sha256_prepare_1_fu_332_ap_start),
    .ap_done(grp_sha256_prepare_1_fu_332_ap_done),
    .ap_idle(grp_sha256_prepare_1_fu_332_ap_idle),
    .ap_ready(grp_sha256_prepare_1_fu_332_ap_ready),
    .input_V_address0(grp_sha256_prepare_1_fu_332_input_V_address0),
    .input_V_ce0(grp_sha256_prepare_1_fu_332_input_V_ce0),
    .input_V_q0(input_V_q0),
    .data_V_address0(grp_sha256_prepare_1_fu_332_data_V_address0),
    .data_V_ce0(grp_sha256_prepare_1_fu_332_data_V_ce0),
    .data_V_we0(grp_sha256_prepare_1_fu_332_data_V_we0),
    .data_V_d0(grp_sha256_prepare_1_fu_332_data_V_d0)
);

sha256_prepare_2 grp_sha256_prepare_2_fu_339(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_sha256_prepare_2_fu_339_ap_start),
    .ap_done(grp_sha256_prepare_2_fu_339_ap_done),
    .ap_idle(grp_sha256_prepare_2_fu_339_ap_idle),
    .ap_ready(grp_sha256_prepare_2_fu_339_ap_ready),
    .input_V_address0(grp_sha256_prepare_2_fu_339_input_V_address0),
    .input_V_ce0(grp_sha256_prepare_2_fu_339_input_V_ce0),
    .input_V_q0(hash1_V_q0),
    .data_V_address0(grp_sha256_prepare_2_fu_339_data_V_address0),
    .data_V_ce0(grp_sha256_prepare_2_fu_339_data_V_ce0),
    .data_V_we0(grp_sha256_prepare_2_fu_339_data_V_we0),
    .data_V_d0(grp_sha256_prepare_2_fu_339_data_V_d0)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_sha256_prepare_1_fu_332_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state3)) begin
            grp_sha256_prepare_1_fu_332_ap_start_reg <= 1'b1;
        end else if ((grp_sha256_prepare_1_fu_332_ap_ready == 1'b1)) begin
            grp_sha256_prepare_1_fu_332_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_sha256_prepare_2_fu_339_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state12)) begin
            grp_sha256_prepare_2_fu_339_ap_start_reg <= 1'b1;
        end else if ((grp_sha256_prepare_2_fu_339_ap_ready == 1'b1)) begin
            grp_sha256_prepare_2_fu_339_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_sha256_transform_1_fu_324_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state14)) begin
            grp_sha256_transform_1_fu_324_ap_start_reg <= 1'b1;
        end else if ((grp_sha256_transform_1_fu_324_ap_ready == 1'b1)) begin
            grp_sha256_transform_1_fu_324_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_sha256_transform_fu_313_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state5))) begin
            grp_sha256_transform_fu_313_ap_start_reg <= 1'b1;
        end else if ((grp_sha256_transform_fu_313_ap_ready == 1'b1)) begin
            grp_sha256_transform_fu_313_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state17)) begin
        i_0_i12_reg_302 <= i_1_reg_400;
    end else if (((1'b1 == ap_CS_fsm_state15) & (grp_sha256_transform_1_fu_324_ap_done == 1'b1))) begin
        i_0_i12_reg_302 <= 4'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        i_0_i_reg_291 <= i_reg_382;
    end else if (((1'b1 == ap_CS_fsm_state8) & (grp_sha256_transform_fu_313_ap_done == 1'b1))) begin
        i_0_i_reg_291 <= 4'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state16)) begin
        i_1_reg_400 <= i_1_fu_368_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        i_reg_382 <= i_fu_351_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln125_fu_345_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state9))) begin
        zext_ln126_reg_387[3 : 0] <= zext_ln126_fu_357_p1[3 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln162_fu_362_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state16))) begin
        zext_ln163_reg_405[3 : 0] <= zext_ln163_fu_374_p1[3 : 0];
    end
end

always @ (*) begin
    if (((icmp_ln162_fu_362_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state16))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln162_fu_362_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state16))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        data_V_1_address0 = grp_sha256_prepare_2_fu_339_data_V_address0;
    end else if ((1'b1 == ap_CS_fsm_state15)) begin
        data_V_1_address0 = grp_sha256_transform_1_fu_324_data_V_address0;
    end else begin
        data_V_1_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        data_V_1_ce0 = grp_sha256_prepare_2_fu_339_data_V_ce0;
    end else if ((1'b1 == ap_CS_fsm_state15)) begin
        data_V_1_ce0 = grp_sha256_transform_1_fu_324_data_V_ce0;
    end else begin
        data_V_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        data_V_1_we0 = grp_sha256_prepare_2_fu_339_data_V_we0;
    end else begin
        data_V_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        data_V_address0 = grp_sha256_prepare_1_fu_332_data_V_address0;
    end else if (((1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state8))) begin
        data_V_address0 = grp_sha256_transform_fu_313_data_V_address0;
    end else begin
        data_V_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        data_V_ce0 = grp_sha256_prepare_1_fu_332_data_V_ce0;
    end else if (((1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state8))) begin
        data_V_ce0 = grp_sha256_transform_fu_313_data_V_ce0;
    end else begin
        data_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        data_V_we0 = grp_sha256_prepare_1_fu_332_data_V_we0;
    end else begin
        data_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        grp_sha256_transform_fu_313_data_V_offset = 1'd1;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        grp_sha256_transform_fu_313_data_V_offset = 1'd0;
    end else begin
        grp_sha256_transform_fu_313_data_V_offset = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        hash1_V_1_address0 = zext_ln126_fu_357_p1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        hash1_V_1_address0 = 64'd6;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        hash1_V_1_address0 = 64'd4;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        hash1_V_1_address0 = 64'd2;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        hash1_V_1_address0 = 64'd0;
    end else if (((1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state8))) begin
        hash1_V_1_address0 = grp_sha256_transform_fu_313_state_V_address0;
    end else begin
        hash1_V_1_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        hash1_V_1_address1 = 64'd7;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        hash1_V_1_address1 = 64'd5;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        hash1_V_1_address1 = 64'd3;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        hash1_V_1_address1 = 64'd1;
    end else if (((1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state8))) begin
        hash1_V_1_address1 = grp_sha256_transform_fu_313_state_V_address1;
    end else begin
        hash1_V_1_address1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state2) | (1'b1 == ap_CS_fsm_state3) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)) | ((1'b1 == ap_CS_fsm_state4) & (grp_sha256_prepare_1_fu_332_ap_done == 1'b1)))) begin
        hash1_V_1_ce0 = 1'b1;
    end else if (((1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state8))) begin
        hash1_V_1_ce0 = grp_sha256_transform_fu_313_state_V_ce0;
    end else begin
        hash1_V_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) | (1'b1 == ap_CS_fsm_state3) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)) | ((1'b1 == ap_CS_fsm_state4) & (grp_sha256_prepare_1_fu_332_ap_done == 1'b1)))) begin
        hash1_V_1_ce1 = 1'b1;
    end else if (((1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state8))) begin
        hash1_V_1_ce1 = grp_sha256_transform_fu_313_state_V_ce1;
    end else begin
        hash1_V_1_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        hash1_V_1_d0 = 32'd528734635;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        hash1_V_1_d0 = 32'd1359893119;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        hash1_V_1_d0 = 32'd1013904242;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        hash1_V_1_d0 = 32'd1779033703;
    end else if (((1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state8))) begin
        hash1_V_1_d0 = grp_sha256_transform_fu_313_state_V_d0;
    end else begin
        hash1_V_1_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        hash1_V_1_d1 = 32'd1541459225;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        hash1_V_1_d1 = 32'd2600822924;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        hash1_V_1_d1 = 32'd2773480762;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        hash1_V_1_d1 = 32'd3144134277;
    end else if (((1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state8))) begin
        hash1_V_1_d1 = grp_sha256_transform_fu_313_state_V_d1;
    end else begin
        hash1_V_1_d1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) | (1'b1 == ap_CS_fsm_state3) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)) | ((1'b1 == ap_CS_fsm_state4) & (grp_sha256_prepare_1_fu_332_ap_done == 1'b1)))) begin
        hash1_V_1_we0 = 1'b1;
    end else if (((1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state8))) begin
        hash1_V_1_we0 = grp_sha256_transform_fu_313_state_V_we0;
    end else begin
        hash1_V_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) | (1'b1 == ap_CS_fsm_state3) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)) | ((1'b1 == ap_CS_fsm_state4) & (grp_sha256_prepare_1_fu_332_ap_done == 1'b1)))) begin
        hash1_V_1_we1 = 1'b1;
    end else if (((1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state8))) begin
        hash1_V_1_we1 = grp_sha256_transform_fu_313_state_V_we1;
    end else begin
        hash1_V_1_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state16)) begin
        hash1_V_2_address0 = zext_ln163_fu_374_p1;
    end else if ((1'b1 == ap_CS_fsm_state13)) begin
        hash1_V_2_address0 = 64'd6;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        hash1_V_2_address0 = 64'd4;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        hash1_V_2_address0 = 64'd2;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        hash1_V_2_address0 = 64'd0;
    end else if ((1'b1 == ap_CS_fsm_state15)) begin
        hash1_V_2_address0 = grp_sha256_transform_1_fu_324_state_V_address0;
    end else begin
        hash1_V_2_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        hash1_V_2_address1 = 64'd7;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        hash1_V_2_address1 = 64'd5;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        hash1_V_2_address1 = 64'd3;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        hash1_V_2_address1 = 64'd1;
    end else if ((1'b1 == ap_CS_fsm_state15)) begin
        hash1_V_2_address1 = grp_sha256_transform_1_fu_324_state_V_address1;
    end else begin
        hash1_V_2_address1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state16) | (1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state12) | ((1'b1 == ap_CS_fsm_state13) & (grp_sha256_prepare_2_fu_339_ap_done == 1'b1)))) begin
        hash1_V_2_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state15)) begin
        hash1_V_2_ce0 = grp_sha256_transform_1_fu_324_state_V_ce0;
    end else begin
        hash1_V_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state12) | ((1'b1 == ap_CS_fsm_state13) & (grp_sha256_prepare_2_fu_339_ap_done == 1'b1)))) begin
        hash1_V_2_ce1 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state15)) begin
        hash1_V_2_ce1 = grp_sha256_transform_1_fu_324_state_V_ce1;
    end else begin
        hash1_V_2_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        hash1_V_2_d0 = 32'd528734635;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        hash1_V_2_d0 = 32'd1359893119;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        hash1_V_2_d0 = 32'd1013904242;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        hash1_V_2_d0 = 32'd1779033703;
    end else if ((1'b1 == ap_CS_fsm_state15)) begin
        hash1_V_2_d0 = grp_sha256_transform_1_fu_324_state_V_d0;
    end else begin
        hash1_V_2_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        hash1_V_2_d1 = 32'd1541459225;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        hash1_V_2_d1 = 32'd2600822924;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        hash1_V_2_d1 = 32'd2773480762;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        hash1_V_2_d1 = 32'd3144134277;
    end else if ((1'b1 == ap_CS_fsm_state15)) begin
        hash1_V_2_d1 = grp_sha256_transform_1_fu_324_state_V_d1;
    end else begin
        hash1_V_2_d1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state12) | ((icmp_ln125_fu_345_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state9)) | ((1'b1 == ap_CS_fsm_state13) & (grp_sha256_prepare_2_fu_339_ap_done == 1'b1)))) begin
        hash1_V_2_we0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state15)) begin
        hash1_V_2_we0 = grp_sha256_transform_1_fu_324_state_V_we0;
    end else begin
        hash1_V_2_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state12) | ((icmp_ln125_fu_345_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state9)) | ((1'b1 == ap_CS_fsm_state13) & (grp_sha256_prepare_2_fu_339_ap_done == 1'b1)))) begin
        hash1_V_2_we1 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state15)) begin
        hash1_V_2_we1 = grp_sha256_transform_1_fu_324_state_V_we1;
    end else begin
        hash1_V_2_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        hash1_V_address0 = zext_ln126_reg_387;
    end else if ((1'b1 == ap_CS_fsm_state13)) begin
        hash1_V_address0 = grp_sha256_prepare_2_fu_339_input_V_address0;
    end else begin
        hash1_V_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        hash1_V_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state13)) begin
        hash1_V_ce0 = grp_sha256_prepare_2_fu_339_input_V_ce0;
    end else begin
        hash1_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        hash1_V_we0 = 1'b1;
    end else begin
        hash1_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state17)) begin
        output_V_ce0 = 1'b1;
    end else begin
        output_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state17)) begin
        output_V_we0 = 1'b1;
    end else begin
        output_V_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            if (((1'b1 == ap_CS_fsm_state4) & (grp_sha256_prepare_1_fu_332_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            if (((1'b1 == ap_CS_fsm_state6) & (grp_sha256_transform_fu_313_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            if (((1'b1 == ap_CS_fsm_state8) & (grp_sha256_transform_fu_313_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end
        end
        ap_ST_fsm_state9 : begin
            if (((icmp_ln125_fu_345_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state9))) begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state12;
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state13;
        end
        ap_ST_fsm_state13 : begin
            if (((1'b1 == ap_CS_fsm_state13) & (grp_sha256_prepare_2_fu_339_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state14;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state13;
            end
        end
        ap_ST_fsm_state14 : begin
            ap_NS_fsm = ap_ST_fsm_state15;
        end
        ap_ST_fsm_state15 : begin
            if (((1'b1 == ap_CS_fsm_state15) & (grp_sha256_transform_1_fu_324_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state16;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state15;
            end
        end
        ap_ST_fsm_state16 : begin
            if (((icmp_ln162_fu_362_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state16))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state17;
            end
        end
        ap_ST_fsm_state17 : begin
            ap_NS_fsm = ap_ST_fsm_state16;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state12 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_state13 = ap_CS_fsm[32'd12];

assign ap_CS_fsm_state14 = ap_CS_fsm[32'd13];

assign ap_CS_fsm_state15 = ap_CS_fsm[32'd14];

assign ap_CS_fsm_state16 = ap_CS_fsm[32'd15];

assign ap_CS_fsm_state17 = ap_CS_fsm[32'd16];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

assign grp_sha256_prepare_1_fu_332_ap_start = grp_sha256_prepare_1_fu_332_ap_start_reg;

assign grp_sha256_prepare_2_fu_339_ap_start = grp_sha256_prepare_2_fu_339_ap_start_reg;

assign grp_sha256_transform_1_fu_324_ap_start = grp_sha256_transform_1_fu_324_ap_start_reg;

assign grp_sha256_transform_fu_313_ap_start = grp_sha256_transform_fu_313_ap_start_reg;

assign i_1_fu_368_p2 = (i_0_i12_reg_302 + 4'd1);

assign i_fu_351_p2 = (i_0_i_reg_291 + 4'd1);

assign icmp_ln125_fu_345_p2 = ((i_0_i_reg_291 == 4'd8) ? 1'b1 : 1'b0);

assign icmp_ln162_fu_362_p2 = ((i_0_i12_reg_302 == 4'd8) ? 1'b1 : 1'b0);

assign input_V_address0 = grp_sha256_prepare_1_fu_332_input_V_address0;

assign input_V_ce0 = grp_sha256_prepare_1_fu_332_input_V_ce0;

assign output_V_address0 = zext_ln163_reg_405;

assign output_V_d0 = hash1_V_2_q0;

assign zext_ln126_fu_357_p1 = i_0_i_reg_291;

assign zext_ln163_fu_374_p1 = i_0_i12_reg_302;

always @ (posedge ap_clk) begin
    zext_ln126_reg_387[63:4] <= 60'b000000000000000000000000000000000000000000000000000000000000;
    zext_ln163_reg_405[63:4] <= 60'b000000000000000000000000000000000000000000000000000000000000;
end

endmodule //sha256d
